"""Update the Sprint Plan Excel with current implementation status.

Marks tasks as Done, In Progress, or To Do based on actual codebase state.
"""
import openpyxl
from openpyxl.styles import Font, PatternFill, Alignment, Border, Side

NAVY    = "1B3A6B"
GOLD    = "C9A84C"
WHITE   = "FFFFFF"
LTGOLD  = "FEF3C7"
LTBLUE  = "DBEAFE"
LTGREEN = "DCFCE7"
LTORANGE= "FFF7ED"
LTRED   = "FEE2E2"
GRAY1   = "F3F4F6"
GRAY2   = "E5E7EB"
TEAL    = "0F766E"
TEAL_LT = "CCFBF1"
GREEN   = "16A34A"
ORANGE  = "EA580C"
RED     = "DC2626"
BLUE    = "2563EB"
MIDGRAY = "6B7280"

def hex_fill(hex_color):
    return PatternFill("solid", fgColor=hex_color)

def border():
    s = Side(style="thin", color="CCCCCC")
    return Border(left=s, right=s, top=s, bottom=s)

# Status mapping: which tasks are Done, In Progress, or To Do
# Based on actual codebase analysis
TASK_STATUS = {
    # ── Sprint 1: Foundation & Ingestion ──
    "T-001": "Done",       # Monorepo + CI/CD - complete
    "T-002": "Done",       # Redis + Celery queue - code exists
    "T-003": "Done",       # PDF extraction - code exists
    "T-004": "Done",       # DOCX + clause segmentation - code exists
    "T-005": "Done",       # OCR fallback (Textract) - code exists
    "T-006": "Done",       # Semantic chunking - code exists
    "T-007": "Done",       # PostgreSQL + pgvector schema - deployed
    "T-008": "Done",       # FastAPI + Auth0 - live on port 8000

    # ── Sprint 2: AI Risk Engine ──
    "T-009": "Done",       # DeepSeek + OpenAI configured as primary/fallback
    "T-010": "Done",       # 12-category risk taxonomy - in risk_engine/taxonomy.py
    "T-011": "In Progress", # Risk clause flagging prompt chain - needs live LLM wiring
    "T-012": "Done",       # Pinecone + RAG pipeline - configured
    "T-013": "Done",       # Severity scoring - code exists in risk_engine/
    "T-014": "To Do",      # LoRA fine-tuning - needs CUAD dataset
    "T-015": "Done",       # Risk flagging output schema - in redline/models.py
    "T-016": "To Do",      # Accuracy evaluation harness
    "T-017": "To Do",      # FP rate monitoring

    # ── Sprint 3: Redline & Benchmarking ──
    "T-018": "Done",       # 8 redline prompt templates - in redline/prompts.py
    "T-019": "Done",       # Redline output formatter - in redline/formatter.py
    "T-020": "Done",       # DOCX tracked-changes export - in export/docx_exporter.py
    "T-021": "Done",       # PDF markup export - in export/pdf_exporter.py
    "T-022": "In Progress", # Benchmark corpus ingestion - code in benchmarking/
    "T-023": "Done",       # Benchmark scoring engine - in benchmarking/scoring_engine.py
    "T-024": "Done",       # Benchmark segmentation - in benchmarking/segmentation.py
    "T-025": "Done",       # Freshness indicator - in benchmarking/freshness.py

    # ── Sprint 4: Dashboard & Reporting ──
    "T-026": "To Do",      # Frontend app scaffold (Next.js)
    "T-027": "To Do",      # Portfolio risk dashboard
    "T-028": "To Do",      # CFO persona view
    "T-029": "To Do",      # Legal persona view
    "T-030": "To Do",      # Procurement persona view
    "T-031": "Done",       # PDF report generator - in export/pdf_exporter.py
    "T-032": "In Progress", # Excel + JSON API - export code exists, API needs testing

    # ── Sprint 5: RBAC & Audit Trail ──
    "T-033": "Done",       # RBAC with permissions - in middleware/auth.py
    "T-034": "To Do",      # SCIM 2.0 provisioning
    "T-035": "To Do",      # SAML 2.0 + OIDC SSO
    "T-036": "Done",       # Audit log - routers/audit.py exists
    "T-037": "Done",       # Audit log export - in export/
    "T-038": "To Do",      # Data encryption at rest
    "T-039": "To Do",      # SOC 2 evidence collection

    # ── Sprint 6: Integrations & API ──
    "T-040": "To Do",      # Salesforce sync
    "T-041": "To Do",      # HubSpot integration
    "T-042": "Done",       # Zapier webhooks - routers/webhooks.py exists
    "T-043": "Done",       # OpenAPI 3.0 docs - auto-generated by FastAPI
    "T-044": "To Do",      # GraphQL API layer
    "T-045": "To Do",      # Python + Node.js SDK
    "T-046": "To Do",      # Counterparty risk scoring
    "T-047": "Done",       # Version diff engine - in redline/diff_engine.py

    # ── Sprint 7: Playbook & Collaboration ──
    "T-048": "To Do",      # No-code playbook builder UI
    "T-049": "To Do",      # Playbook versioning
    "T-050": "To Do",      # Playbook template library
    "T-051": "To Do",      # Real-time collaboration
    "T-052": "To Do",      # Clause-level commenting
    "T-053": "To Do",      # Multi-language support
    "T-054": "To Do",      # Email intake plugin

    # ── Sprint 8: Launch Readiness ──
    "T-055": "To Do",      # White-label OEM mode
    "T-056": "To Do",      # Stripe billing
    "T-057": "To Do",      # Free trial flow
    "T-058": "To Do",      # Datadog + Sentry
    "T-059": "To Do",      # Hallucination detection
    "T-060": "To Do",      # Load testing
    "T-061": "To Do",      # ESG clause analysis
    "T-062": "To Do",      # AI Negotiation Coach
}

STATUS_COLORS = {
    "Done": (GREEN, LTGREEN),
    "In Progress": (ORANGE, LTORANGE),
    "To Do": (MIDGRAY, GRAY1),
}

def update_excel():
    wb = openpyxl.load_workbook("/Volumes/home/ContractRiskEdge/output/AI_Contract_Risk_Analyzer_Sprint_Plan.xlsx")
    ws = wb["🗓️ Sprint Plan"]

    for row in ws.iter_rows(min_row=4, max_row=65, values_only=False):
        tid_cell = row[2]  # Column C = Task ID
        status_cell = row[7]  # Column H = Status
        done_cell = row[9]  # Column J = Done checkbox

        tid = tid_cell.value
        if tid and tid in TASK_STATUS:
            new_status = TASK_STATUS[tid]
            fg_color, bg_color = STATUS_COLORS[new_status]

            # Update status cell
            status_cell.value = new_status
            status_cell.font = Font(bold=True, size=9, color=fg_color, name="Arial")
            status_cell.fill = hex_fill(bg_color)
            status_cell.alignment = Alignment(horizontal="center", vertical="center", wrap_text=True)
            status_cell.border = border()

            # Update checkbox
            if new_status == "Done":
                done_cell.value = "☑"
                done_cell.font = Font(size=12, color=GREEN, name="Arial")
            elif new_status == "In Progress":
                done_cell.value = "◐"
                done_cell.font = Font(size=12, color=ORANGE, name="Arial")
            else:
                done_cell.value = "☐"
                done_cell.font = Font(size=12, color=NAVY, name="Arial")
            done_cell.fill = hex_fill(WHITE)
            done_cell.alignment = Alignment(horizontal="center", vertical="center")
            done_cell.border = border()

    # Update Dashboard sheet summary
    ws1 = wb["📊 Dashboard"]
    
    # Count by status
    status_counts = {"Done": 0, "In Progress": 0, "To Do": 0}
    for s in TASK_STATUS.values():
        status_counts[s] += 1
    
    # Find and update summary cells (assuming they're in a known location)
    # Write summary to a new area
    print(f"Status Summary:")
    print(f"  Done: {status_counts['Done']} / 62")
    print(f"  In Progress: {status_counts['In Progress']} / 62")
    print(f"  To Do: {status_counts['To Do']} / 62")
    print(f"  Progress: {status_counts['Done']/62*100:.1f}%")

    wb.save("/Volumes/home/ContractRiskEdge/output/AI_Contract_Risk_Analyzer_Sprint_Plan.xlsx")
    print("\n✅ Sprint Plan updated and saved!")

if __name__ == "__main__":
    update_excel()
