/**
 * Policy Engine mock data — realistic enterprise policies.
 */

import type { PolicyDefinition } from "@/services/api/policy";

export const mockPolicies: PolicyDefinition[] = [
  {
    policy_id: "pol-001",
    name: "IP Ownership — Customer Retains Deliverables",
    description: "Customer must retain full ownership of all custom deliverables, work product, and associated IP developed specifically for them.",
    scope: "tenant",
    category: "intellectual_property",
    effect: "flag_for_review",
    priority: 100,
    enabled: true,
    version: 3,
    tags: ["ip", "ownership", "deliverables", "critical"],
    rules: {
      group_id: "g1",
      type: "AND",
      conditions: [
        { condition_id: "c1", field: "clause_category", operator: "equals", value: "intellectual_property", label: "Clause is IP-related" },
        { condition_id: "c2", field: "clause_text", operator: "contains", value: "retains exclusive rights", label: "Vendor retains exclusive rights" },
      ],
    },
    valid_from: "2025-01-01T00:00:00Z",
    valid_until: null,
    created_by: "system",
    created_at: "2025-01-01T00:00:00Z",
    updated_at: "2026-05-15T00:00:00Z",
  },
  {
    policy_id: "pol-002",
    name: "Liability Cap — Mutual 2x Annual Fees",
    description: "Liability must be capped at no more than 2x annual contract value, mutually applicable to both parties.",
    scope: "tenant",
    category: "liability",
    effect: "flag_for_review",
    priority: 90,
    enabled: true,
    version: 2,
    tags: ["liability", "cap", "mutual", "high"],
    rules: {
      group_id: "g2",
      type: "AND",
      conditions: [
        { condition_id: "c3", field: "clause_category", operator: "equals", value: "liability", label: "Clause is liability-related" },
        { condition_id: "c4", field: "clause_text", operator: "not_contains", value: "mutual", label: "Liability is not mutual" },
      ],
    },
    valid_from: "2025-01-01T00:00:00Z",
    valid_until: null,
    created_by: "system",
    created_at: "2025-01-01T00:00:00Z",
    updated_at: "2026-04-20T00:00:00Z",
  },
  {
    policy_id: "pol-003",
    name: "Indemnification — Mutual With IP Carve-out",
    description: "Indemnification must be mutual with exclusions for IP infringement, confidentiality breach, and statutory obligations.",
    scope: "tenant",
    category: "indemnification",
    effect: "flag_for_review",
    priority: 85,
    enabled: true,
    version: 2,
    tags: ["indemnification", "mutual", "ip", "high"],
    rules: {
      group_id: "g3",
      type: "AND",
      conditions: [
        { condition_id: "c5", field: "clause_category", operator: "equals", value: "indemnification", label: "Clause is indemnification" },
        { condition_id: "c6", field: "clause_text", operator: "not_contains", value: "mutual", label: "Indemnification is one-sided" },
      ],
    },
    valid_from: "2025-01-01T00:00:00Z",
    valid_until: null,
    created_by: "system",
    created_at: "2025-01-01T00:00:00Z",
    updated_at: "2026-05-10T00:00:00Z",
  },
  {
    policy_id: "pol-004",
    name: "Confidentiality — 3-Year Minimum Survival",
    description: "Confidentiality obligations must survive termination for at least 3 years. Trade secrets must survive indefinitely.",
    scope: "tenant",
    category: "confidentiality",
    effect: "flag_for_review",
    priority: 80,
    enabled: true,
    version: 1,
    tags: ["confidentiality", "survival", "medium"],
    rules: {
      group_id: "g4",
      type: "AND",
      conditions: [
        { condition_id: "c7", field: "clause_category", operator: "equals", value: "confidentiality", label: "Clause is confidentiality" },
        { condition_id: "c8", field: "clause_text", operator: "matches_regex", value: "survives?\\s*(?:termination|expiry).{0,50}(?:year|month)", label: "Has survival period" },
      ],
    },
    valid_from: "2025-01-01T00:00:00Z",
    valid_until: null,
    created_by: "system",
    created_at: "2025-01-01T00:00:00Z",
    updated_at: "2026-03-01T00:00:00Z",
  },
  {
    policy_id: "pol-005",
    name: "Data Privacy — DPA Required",
    description: "A Data Processing Agreement (DPA) must be attached for any processing of personal data. GDPR Art 28 compliance required.",
    scope: "tenant",
    category: "data_privacy",
    effect: "block",
    priority: 95,
    enabled: true,
    version: 3,
    tags: ["privacy", "dpa", "gdpr", "critical"],
    rules: {
      group_id: "g5",
      type: "AND",
      conditions: [
        { condition_id: "c9", field: "clause_category", operator: "equals", value: "data_privacy", label: "Clause is data privacy" },
        { condition_id: "c10", field: "clause_text", operator: "not_contains", value: "data processing agreement", label: "No DPA referenced" },
      ],
    },
    valid_from: "2025-01-01T00:00:00Z",
    valid_until: null,
    created_by: "system",
    created_at: "2025-01-01T00:00:00Z",
    updated_at: "2026-05-20T00:00:00Z",
  },
  {
    policy_id: "pol-006",
    name: "SLA — 99.9% Uptime Minimum",
    description: "Vendor must commit to at least 99.9% service availability with service credits for breaches.",
    scope: "tenant",
    category: "sla",
    effect: "flag_for_review",
    priority: 75,
    enabled: true,
    version: 1,
    tags: ["sla", "uptime", "service", "medium"],
    rules: {
      group_id: "g6",
      type: "AND",
      conditions: [
        { condition_id: "c11", field: "clause_category", operator: "equals", value: "sla", label: "Clause is SLA" },
        { condition_id: "c12", field: "clause_text", operator: "matches_regex", value: "99\\.?\\s*9\\s*%", label: "Uptime below 99.9%" },
      ],
    },
    valid_from: "2025-01-01T00:00:00Z",
    valid_until: null,
    created_by: "system",
    created_at: "2025-01-01T00:00:00Z",
    updated_at: "2026-02-15T00:00:00Z",
  },
  {
    policy_id: "pol-007",
    name: "Termination — 30-Day Convenience",
    description: "Customer must have the right to terminate for convenience with 30 days notice, without penalty.",
    scope: "tenant",
    category: "termination",
    effect: "flag_for_review",
    priority: 70,
    enabled: true,
    version: 1,
    tags: ["termination", "convenience", "medium"],
    rules: {
      group_id: "g7",
      type: "AND",
      conditions: [
        { condition_id: "c13", field: "clause_category", operator: "equals", value: "termination", label: "Clause is termination" },
        { condition_id: "c14", field: "clause_text", operator: "not_contains", value: "convenience", label: "No termination for convenience" },
      ],
    },
    valid_from: "2025-01-01T00:00:00Z",
    valid_until: null,
    created_by: "system",
    created_at: "2025-01-01T00:00:00Z",
    updated_at: "2026-01-10T00:00:00Z",
  },
  {
    policy_id: "pol-008",
    name: "Non-Compete — Restrict Scope",
    description: "Non-compete clauses must be limited in scope, geography, and duration. Broad non-competes are blocked.",
    scope: "tenant",
    category: "non_compete",
    effect: "block",
    priority: 65,
    enabled: true,
    version: 2,
    tags: ["non-compete", "restrictive", "high"],
    rules: {
      group_id: "g8",
      type: "AND",
      conditions: [
        { condition_id: "c15", field: "clause_category", operator: "equals", value: "non_compete", label: "Clause is non-compete" },
        { condition_id: "c16", field: "clause_text", operator: "matches_regex", value: "(?:broad|unlimited|any\\s+(?:business|industry|field))", label: "Broad non-compete scope" },
      ],
    },
    valid_from: "2025-01-01T00:00:00Z",
    valid_until: null,
    created_by: "system",
    created_at: "2025-01-01T00:00:00Z",
    updated_at: "2026-04-01T00:00:00Z",
  },
  {
    policy_id: "pol-009",
    name: "Governing Law — Customer Jurisdiction",
    description: "Governing law and venue must be in Customer's jurisdiction, not vendor's.",
    scope: "tenant",
    category: "governing_law",
    effect: "flag_for_review",
    priority: 60,
    enabled: true,
    version: 1,
    tags: ["governing_law", "venue", "jurisdiction", "medium"],
    rules: {
      group_id: "g9",
      type: "AND",
      conditions: [
        { condition_id: "c17", field: "clause_category", operator: "equals", value: "governing_law", label: "Clause is governing law" },
        { condition_id: "c18", field: "clause_text", operator: "not_contains", value: "customer", label: "Venue is not customer-friendly" },
      ],
    },
    valid_from: "2025-01-01T00:00:00Z",
    valid_until: null,
    created_by: "system",
    created_at: "2025-01-01T00:00:00Z",
    updated_at: "2026-03-15T00:00:00Z",
  },
  {
    policy_id: "pol-010",
    name: "Insurance — Minimum Coverage Requirements",
    description: "Vendor must carry minimum insurance coverage: Commercial General Liability $2M, Cyber $5M, Professional Liability $3M.",
    scope: "tenant",
    category: "insurance",
    effect: "flag_for_review",
    priority: 55,
    enabled: false,
    version: 1,
    tags: ["insurance", "coverage", "minimum"],
    rules: {
      group_id: "g10",
      type: "AND",
      conditions: [
        { condition_id: "c19", field: "clause_category", operator: "equals", value: "insurance", label: "Clause is insurance" },
        { condition_id: "c20", field: "clause_text", operator: "matches_regex", value: "general\\s+liability.*(?:\\$|million|m)", label: "May have GL coverage" },
      ],
    },
    valid_from: "2025-06-01T00:00:00Z",
    valid_until: null,
    created_by: "system",
    created_at: "2025-06-01T00:00:00Z",
    updated_at: "2026-05-01T00:00:00Z",
  },
];

export const mockPolicyCategories = [
  { id: "intellectual_property", label: "Intellectual Property", count: 1, severity: "critical" as const, icon: "Shield" },
  { id: "liability", label: "Liability", count: 1, severity: "high" as const, icon: "AlertTriangle" },
  { id: "indemnification", label: "Indemnification", count: 1, severity: "high" as const, icon: "Scale" },
  { id: "confidentiality", label: "Confidentiality", count: 1, severity: "medium" as const, icon: "Lock" },
  { id: "data_privacy", label: "Data Privacy", count: 1, severity: "critical" as const, icon: "Shield" },
  { id: "sla", label: "SLA", count: 1, severity: "medium" as const, icon: "Clock" },
  { id: "termination", label: "Termination", count: 1, severity: "medium" as const, icon: "XCircle" },
  { id: "non_compete", label: "Non-Compete", count: 1, severity: "high" as const, icon: "Ban" },
  { id: "governing_law", label: "Governing Law", count: 1, severity: "medium" as const, icon: "BookOpen" },
  { id: "insurance", label: "Insurance", count: 1, severity: "low" as const, icon: "FileText" },
];

export const mockViolations = [
  {
    id: "viol-001",
    policy_id: "pol-001",
    policy_name: "IP Ownership — Customer Retains Deliverables",
    contract_name: "Master Services Agreement — Acme Corp",
    clause_text: "Consultant retains all right, title, and interest in and to any deliverables, work product, and intellectual property developed under this Agreement.",
    severity: "critical" as const,
    status: "open" as const,
    detected_at: "2026-05-28T10:30:00Z",
    finding_id: "find-001",
  },
  {
    id: "viol-002",
    policy_id: "pol-003",
    policy_name: "Indemnification — Mutual With IP Carve-out",
    contract_name: "Master Services Agreement — Acme Corp",
    clause_text: "Vendor shall indemnify Customer against all third-party claims. Customer shall indemnify Vendor against all third-party claims.",
    severity: "high" as const,
    status: "open" as const,
    detected_at: "2026-05-28T10:30:00Z",
    finding_id: "find-003",
  },
  {
    id: "viol-003",
    policy_id: "pol-005",
    policy_name: "Data Privacy — DPA Required",
    contract_name: "SaaS Agreement — TechStart Inc",
    clause_text: "Vendor may process Customer data for service delivery purposes.",
    severity: "critical" as const,
    status: "open" as const,
    detected_at: "2026-05-29T14:00:00Z",
    finding_id: "find-005",
  },
  {
    id: "viol-004",
    policy_id: "pol-002",
    policy_name: "Liability Cap — Mutual 2x Annual Fees",
    contract_name: "Professional Services Agreement — Global Corp",
    clause_text: "Vendor's maximum liability shall not exceed the fees paid in the prior 12 months. Customer's liability is unlimited.",
    severity: "high" as const,
    status: "open" as const,
    detected_at: "2026-05-27T09:00:00Z",
    finding_id: "find-002",
  },
  {
    id: "viol-005",
    policy_id: "pol-007",
    policy_name: "Termination — 30-Day Convenience",
    contract_name: "Professional Services Agreement — Global Corp",
    clause_text: "This Agreement may be terminated by either party upon written notice. Early termination fees may apply.",
    severity: "medium" as const,
    status: "resolved" as const,
    detected_at: "2026-05-25T11:00:00Z",
    finding_id: "find-007",
  },
  {
    id: "viol-006",
    policy_id: "pol-008",
    policy_name: "Non-Compete — Restrict Scope",
    contract_name: "Consulting Agreement — Beta LLC",
    clause_text: "Consultant shall not engage in any business that competes with Customer in any industry worldwide for a period of 5 years.",
    severity: "high" as const,
    status: "open" as const,
    detected_at: "2026-05-30T08:00:00Z",
    finding_id: "find-008",
  },
];
