"""initial schema

Revision ID: 5772cbcfe2b2
Revises: 
Create Date: 2026-05-15 16:17:34.469780

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5772cbcfe2b2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_prompt_versions',
    sa.Column('version_id', sa.UUID(), nullable=False),
    sa.Column('prompt_key', sa.Text(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('template', sa.Text(), nullable=False),
    sa.Column('system_prompt', sa.Text(), nullable=True),
    sa.Column('model', sa.Text(), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('max_tokens', sa.Integer(), nullable=True),
    sa.Column('response_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('change_notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('version_id'),
    sa.UniqueConstraint('prompt_key', 'version', name='uq_ai_prompt_template_version')
    )
    op.create_index(op.f('ix_ai_prompt_versions_prompt_key'), 'ai_prompt_versions', ['prompt_key'], unique=False)
    op.create_table('allowed_upload_types',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('mime_type', sa.Text(), nullable=False),
    sa.Column('extension', sa.Text(), nullable=False),
    sa.Column('magic_bytes_hex', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mime_type')
    )
    op.create_table('tenants',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('domain', sa.Text(), nullable=True),
    sa.Column('plan', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('max_users', sa.Integer(), nullable=False),
    sa.Column('max_documents', sa.Integer(), nullable=False),
    sa.Column('features', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.Text(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.Text(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('tenant_id')
    )
    op.create_table('ai_cache_entries',
    sa.Column('cache_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('prompt_hash', sa.Text(), nullable=False),
    sa.Column('prompt_key', sa.Text(), nullable=False),
    sa.Column('model', sa.Text(), nullable=False),
    sa.Column('response', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('hit_count', sa.Integer(), nullable=False),
    sa.Column('ttl_seconds', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.tenant_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('cache_id')
    )
    op.create_index(op.f('ix_ai_cache_entries_prompt_hash'), 'ai_cache_entries', ['prompt_hash'], unique=False)
    op.create_index(op.f('ix_ai_cache_entries_tenant_id'), 'ai_cache_entries', ['tenant_id'], unique=False)
    op.create_table('escalation_rules',
    sa.Column('rule_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('trigger_event', sa.Text(), nullable=False),
    sa.Column('condition', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('escalation_chain', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('max_escalation_level', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.tenant_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('rule_id')
    )
    op.create_table('governance_audit_events',
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.Text(), nullable=False),
    sa.Column('entity_type', sa.Text(), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('actor_id', sa.Text(), nullable=False),
    sa.Column('actor_role', sa.Text(), nullable=True),
    sa.Column('previous_state', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_state', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('change_summary', sa.Text(), nullable=True),
    sa.Column('correlation_id', sa.Text(), nullable=True),
    sa.Column('request_id', sa.Text(), nullable=True),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.tenant_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_index(op.f('ix_governance_audit_events_created_at'), 'governance_audit_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_governance_audit_events_event_type'), 'governance_audit_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_governance_audit_events_tenant_id'), 'governance_audit_events', ['tenant_id'], unique=False)
    op.create_table('legal_playbooks',
    sa.Column('playbook_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('jurisdiction', sa.Text(), nullable=True),
    sa.Column('practice_area', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'published', 'archived', 'superseded', name='playbook_status'), nullable=False),
    sa.Column('active_version_id', sa.UUID(), nullable=True),
    sa.Column('version_count', sa.Integer(), nullable=False),
    sa.Column('tags', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_by', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.tenant_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('playbook_id')
    )
    op.create_index(op.f('ix_legal_playbooks_tenant_id'), 'legal_playbooks', ['tenant_id'], unique=False)
    op.create_table('notification_preferences',
    sa.Column('preference_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.Text(), nullable=False),
    sa.Column('notification_type', sa.Text(), nullable=False),
    sa.Column('channel', sa.Text(), nullable=False),
    sa.Column('digest_frequency', sa.Text(), nullable=True),
    sa.Column('is_muted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.tenant_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('preference_id'),
    sa.UniqueConstraint('tenant_id', 'user_id', 'notification_type', name='uq_notify_pref_tenant_user_type')
    )
    op.create_index(op.f('ix_notification_preferences_user_id'), 'notification_preferences', ['user_id'], unique=False)
    op.create_table('notifications',
    sa.Column('notification_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.Text(), nullable=False),
    sa.Column('type', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('severity', sa.Text(), nullable=False),
    sa.Column('entity_type', sa.Text(), nullable=True),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('action_url', sa.Text(), nullable=True),
    sa.Column('channel', sa.Text(), nullable=False),
    sa.Column('delivery_status', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dedup_key', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.tenant_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('notification_id')
    )
    op.create_index(op.f('ix_notifications_created_at'), 'notifications', ['created_at'], unique=False)
    op.create_index(op.f('ix_notifications_dedup_key'), 'notifications', ['dedup_key'], unique=False)
    op.create_index(op.f('ix_notifications_tenant_id'), 'notifications', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('retrieval_metrics',
    sa.Column('metric_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('total_queries', sa.Integer(), nullable=False),
    sa.Column('avg_latency_ms', sa.Float(), nullable=True),
    sa.Column('p50_latency_ms', sa.Float(), nullable=True),
    sa.Column('p95_latency_ms', sa.Float(), nullable=True),
    sa.Column('p99_latency_ms', sa.Float(), nullable=True),
    sa.Column('zero_result_rate', sa.Float(), nullable=True),
    sa.Column('avg_result_count', sa.Float(), nullable=True),
    sa.Column('cache_hit_rate', sa.Float(), nullable=True),
    sa.Column('strategy_breakdown', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.tenant_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('metric_id')
    )
    op.create_table('search_queries',
    sa.Column('query_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.Text(), nullable=True),
    sa.Column('query_text', sa.Text(), nullable=False),
    sa.Column('normalized_query', sa.Text(), nullable=True),
    sa.Column('query_type', sa.Text(), nullable=True),
    sa.Column('result_count', sa.Integer(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('retrieval_strategy', sa.Text(), nullable=True),
    sa.Column('filters', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.tenant_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('query_id')
    )
    op.create_index(op.f('ix_search_queries_created_at'), 'search_queries', ['created_at'], unique=False)
    op.create_index(op.f('ix_search_queries_tenant_id'), 'search_queries', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_search_queries_user_id'), 'search_queries', ['user_id'], unique=False)
    op.create_table('semantic_cache',
    sa.Column('cache_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('query_hash', sa.Text(), nullable=False),
    sa.Column('query_embedding', sa.Float(), nullable=True),
    sa.Column('query_text', sa.Text(), nullable=False),
    sa.Column('results', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('result_count', sa.Integer(), nullable=False),
    sa.Column('hit_count', sa.Integer(), nullable=False),
    sa.Column('last_hit_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ttl_seconds', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.tenant_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('cache_id'),
    sa.UniqueConstraint('tenant_id', 'query_hash', name='uq_semantic_cache_tenant_query')
    )
    op.create_index(op.f('ix_semantic_cache_expires_at'), 'semantic_cache', ['expires_at'], unique=False)
    op.create_index(op.f('ix_semantic_cache_query_hash'), 'semantic_cache', ['query_hash'], unique=False)
    op.create_index(op.f('ix_semantic_cache_tenant_id'), 'semantic_cache', ['tenant_id'], unique=False)
    op.create_table('sla_policies',
    sa.Column('policy_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('workflow_type', sa.Text(), nullable=False),
    sa.Column('priority', sa.Text(), nullable=False),
    sa.Column('target_minutes', sa.Integer(), nullable=False),
    sa.Column('warning_threshold_percent', sa.Float(), nullable=False),
    sa.Column('escalation_after_minutes', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.tenant_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('policy_id'),
    sa.UniqueConstraint('tenant_id', 'workflow_type', 'priority', name='uq_notify_workflow_tenant_type_priority')
    )
    op.create_table('upload_sessions',
    sa.Column('upload_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.Text(), nullable=False),
    sa.Column('filename', sa.Text(), nullable=False),
    sa.Column('content_type', sa.Text(), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=False),
    sa.Column('client_checksum_sha256', sa.Text(), nullable=True),
    sa.Column('server_checksum_sha256', sa.Text(), nullable=True),
    sa.Column('storage_key', sa.Text(), nullable=True),
    sa.Column('storage_bucket', sa.Text(), nullable=True),
    sa.Column('ingestion_state', sa.Enum('uploaded', 'validating', 'validated', 'storage_confirmed', 'ocr_pending', 'ocr_processing', 'ocr_complete', 'chunking_pending', 'embedding_pending', 'analysis_pending', 'review_ready', 'failed', 'cancelled', 'quarantined', name='ingestion_state'), nullable=False),
    sa.Column('ingestion_error', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('last_retry_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('mime_validated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('magic_bytes_validated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('checksum_validated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('malware_scan_result', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('correlation_id', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.tenant_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('upload_id'),
    sa.UniqueConstraint('tenant_id', 'upload_id', name='uq_upload_tenant')
    )
    op.create_index(op.f('ix_upload_sessions_ingestion_state'), 'upload_sessions', ['ingestion_state'], unique=False)
    op.create_index(op.f('ix_upload_sessions_tenant_id'), 'upload_sessions', ['tenant_id'], unique=False)
    op.create_table('workflow_events',
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.Text(), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('correlation_id', sa.Text(), nullable=True),
    sa.Column('entity_type', sa.Text(), nullable=True),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('actor_id', sa.Text(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('processed', sa.Boolean(), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.tenant_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_index(op.f('ix_workflow_events_event_type'), 'workflow_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_workflow_events_tenant_id'), 'workflow_events', ['tenant_id'], unique=False)
    op.create_table('workflow_timers',
    sa.Column('timer_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('timer_type', sa.Text(), nullable=False),
    sa.Column('entity_type', sa.Text(), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('target_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('action_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('fired', sa.Boolean(), nullable=False),
    sa.Column('fired_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.tenant_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('timer_id')
    )
    op.create_index(op.f('ix_workflow_timers_target_time'), 'workflow_timers', ['target_time'], unique=False)
    op.create_index(op.f('ix_workflow_timers_tenant_id'), 'workflow_timers', ['tenant_id'], unique=False)
    op.create_table('ai_execution_runs',
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('upload_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.Text(), nullable=True),
    sa.Column('analysis_type', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'processing', 'completed', 'failed', 'cancelled', 'awaiting_approval', name='ai_exec_status'), nullable=False),
    sa.Column('model', sa.Text(), nullable=False),
    sa.Column('provider', sa.Text(), nullable=False),
    sa.Column('total_chunks', sa.Integer(), nullable=False),
    sa.Column('chunks_used', sa.Integer(), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('findings_count', sa.Integer(), nullable=False),
    sa.Column('redlines_count', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.tenant_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['upload_id'], ['upload_sessions.upload_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('run_id')
    )
    op.create_index(op.f('ix_ai_execution_runs_tenant_id'), 'ai_execution_runs', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_ai_execution_runs_upload_id'), 'ai_execution_runs', ['upload_id'], unique=False)
    op.create_table('approval_thresholds',
    sa.Column('threshold_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('playbook_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('threshold_type', sa.Text(), nullable=False),
    sa.Column('operator', sa.Text(), nullable=False),
    sa.Column('min_value', sa.Float(), nullable=True),
    sa.Column('max_value', sa.Float(), nullable=True),
    sa.Column('target_category', sa.Text(), nullable=True),
    sa.Column('approval_role', sa.Text(), nullable=False),
    sa.Column('approval_level', sa.Integer(), nullable=False),
    sa.Column('fallback_approval_role', sa.Text(), nullable=True),
    sa.Column('auto_approve', sa.Boolean(), nullable=False),
    sa.Column('auto_approve_conditions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('sla_hours', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['playbook_id'], ['legal_playbooks.playbook_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.tenant_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('threshold_id')
    )
    op.create_index(op.f('ix_approval_thresholds_playbook_id'), 'approval_thresholds', ['playbook_id'], unique=False)
    op.create_index(op.f('ix_approval_thresholds_tenant_id'), 'approval_thresholds', ['tenant_id'], unique=False)
    op.create_table('chunks',
    sa.Column('chunk_id', sa.UUID(), nullable=False),
    sa.Column('upload_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('page_numbers', postgresql.ARRAY(sa.Integer()), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('text_length', sa.Integer(), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=False),
    sa.Column('chunking_strategy', sa.Enum('semantic', 'fixed_size', 'clause_aware', 'heading_aware', name='chunking_strategy'), nullable=False),
    sa.Column('section_heading', sa.Text(), nullable=True),
    sa.Column('clause_type', sa.Text(), nullable=True),
    sa.Column('embedding', sa.Float(), nullable=True),
    sa.Column('embedding_model', sa.Text(), nullable=True),
    sa.Column('embedding_dimension', sa.Integer(), nullable=True),
    sa.Column('embedding_status', sa.Enum('pending', 'processing', 'completed', 'failed', 'stale', name='embedding_status'), nullable=False),
    sa.Column('checksum', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_duplicate', sa.Boolean(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('token_count >= 1', name='ck_chunks_token_count_positive'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.tenant_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['upload_id'], ['upload_sessions.upload_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('chunk_id'),
    sa.UniqueConstraint('upload_id', 'chunk_index', name='uq_chunk_per_upload')
    )
    op.create_index(op.f('ix_chunks_checksum'), 'chunks', ['checksum'], unique=False)
    op.create_index(op.f('ix_chunks_tenant_id'), 'chunks', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_chunks_upload_id'), 'chunks', ['upload_id'], unique=False)
    op.create_table('contract_reviews',
    sa.Column('review_id', sa.UUID(), nullable=False),
    sa.Column('upload_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('contract_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'ai_analyzed', 'in_review', 'pending_approval', 'approved', 'rejected', 'escalated', 'closed', name='review_status'), nullable=False),
    sa.Column('assigned_to', sa.Text(), nullable=True),
    sa.Column('assigned_by', sa.Text(), nullable=True),
    sa.Column('priority', sa.Text(), nullable=False),
    sa.Column('sla_deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sla_breached', sa.Boolean(), nullable=False),
    sa.Column('finding_count', sa.Integer(), nullable=False),
    sa.Column('redline_count', sa.Integer(), nullable=False),
    sa.Column('comment_count', sa.Integer(), nullable=False),
    sa.Column('escalation_count', sa.Integer(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_by', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.tenant_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['upload_id'], ['upload_sessions.upload_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('review_id')
    )
    op.create_index(op.f('ix_contract_reviews_assigned_to'), 'contract_reviews', ['assigned_to'], unique=False)
    op.create_index(op.f('ix_contract_reviews_tenant_id'), 'contract_reviews', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_contract_reviews_upload_id'), 'contract_reviews', ['upload_id'], unique=False)
    op.create_table('document_pages',
    sa.Column('page_id', sa.UUID(), nullable=False),
    sa.Column('upload_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('text_length', sa.Integer(), nullable=False),
    sa.Column('extraction_method', sa.Enum('pymupdf_direct', 'pymupdf_ocr', 'tesseract_ocr', 'docx_parse', 'txt_parse', 'ocr_fallback', name='extraction_method'), nullable=False),
    sa.Column('extraction_status', sa.Enum('pending', 'processing', 'completed', 'failed', 'skipped', name='extraction_status'), nullable=False),
    sa.Column('ocr_confidence', sa.Float(), nullable=True),
    sa.Column('char_count', sa.Integer(), nullable=False),
    sa.Column('word_count', sa.Integer(), nullable=False),
    sa.Column('symbol_count', sa.Integer(), nullable=False),
    sa.Column('blank_ratio', sa.Float(), nullable=True),
    sa.Column('page_width_pts', sa.Float(), nullable=True),
    sa.Column('page_height_pts', sa.Float(), nullable=True),
    sa.Column('rotation_degrees', sa.Integer(), nullable=True),
    sa.Column('has_text_layer', sa.Boolean(), nullable=True),
    sa.Column('processing_time_ms', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('ocr_confidence >= 0 AND ocr_confidence <= 1', name='ck_document_pages_ocr_confidence_range'),
    sa.CheckConstraint('page_number >= 1', name='ck_document_pages_page_number_positive'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.tenant_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['upload_id'], ['upload_sessions.upload_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('page_id'),
    sa.UniqueConstraint('upload_id', 'page_number', name='uq_page_per_upload')
    )
    op.create_index(op.f('ix_document_pages_tenant_id'), 'document_pages', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_document_pages_upload_id'), 'document_pages', ['upload_id'], unique=False)
    op.create_table('embedding_runs',
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('upload_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('model', sa.Text(), nullable=False),
    sa.Column('dimension', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'processing', 'completed', 'failed', 'stale', name='embedding_run_status'), nullable=False),
    sa.Column('total_chunks', sa.Integer(), nullable=False),
    sa.Column('chunks_embedded', sa.Integer(), nullable=False),
    sa.Column('chunks_failed', sa.Integer(), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('total_cost_usd', sa.Float(), nullable=False),
    sa.Column('avg_latency_ms', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('retry_number', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.tenant_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['upload_id'], ['upload_sessions.upload_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('run_id')
    )
    op.create_index(op.f('ix_embedding_runs_upload_id'), 'embedding_runs', ['upload_id'], unique=False)
    op.create_table('escalation_events',
    sa.Column('escalation_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('rule_id', sa.UUID(), nullable=True),
    sa.Column('entity_type', sa.Text(), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('escalated_by', sa.Text(), nullable=True),
    sa.Column('escalated_to', sa.Text(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['rule_id'], ['escalation_rules.rule_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.tenant_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('escalation_id')
    )
    op.create_index(op.f('ix_escalation_events_tenant_id'), 'escalation_events', ['tenant_id'], unique=False)
    op.create_table('extraction_failures',
    sa.Column('failure_id', sa.UUID(), nullable=False),
    sa.Column('upload_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('failure_type', sa.Text(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=False),
    sa.Column('error_detail', sa.Text(), nullable=True),
    sa.Column('method_attempted', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.tenant_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['upload_id'], ['upload_sessions.upload_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('failure_id')
    )
    op.create_index(op.f('ix_extraction_failures_upload_id'), 'extraction_failures', ['upload_id'], unique=False)
    op.create_table('extraction_runs',
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('upload_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('method', sa.Enum('pymupdf_direct', 'pymupdf_ocr', 'tesseract_ocr', 'docx_parse', 'txt_parse', 'ocr_fallback', name='extraction_method_run'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'processing', 'completed', 'failed', 'skipped', name='extraction_run_status'), nullable=False),
    sa.Column('total_pages', sa.Integer(), nullable=False),
    sa.Column('pages_extracted', sa.Integer(), nullable=False),
    sa.Column('pages_failed', sa.Integer(), nullable=False),
    sa.Column('total_chars', sa.BigInteger(), nullable=False),
    sa.Column('ocr_required', sa.Boolean(), nullable=True),
    sa.Column('ocr_engine_used', sa.Text(), nullable=True),
    sa.Column('avg_confidence', sa.Float(), nullable=True),
    sa.Column('total_processing_time_ms', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('retry_number', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.tenant_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['upload_id'], ['upload_sessions.upload_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('run_id')
    )
    op.create_index(op.f('ix_extraction_runs_upload_id'), 'extraction_runs', ['upload_id'], unique=False)
    op.create_table('notification_deliveries',
    sa.Column('delivery_id', sa.UUID(), nullable=False),
    sa.Column('notification_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('channel', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_retry_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['notification_id'], ['notifications.notification_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.tenant_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('delivery_id')
    )
    op.create_index(op.f('ix_notification_deliveries_notification_id'), 'notification_deliveries', ['notification_id'], unique=False)
    op.create_table('playbook_versions',
    sa.Column('version_id', sa.UUID(), nullable=False),
    sa.Column('playbook_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('version_label', sa.Text(), nullable=True),
    sa.Column('change_notes', sa.Text(), nullable=True),
    sa.Column('snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('parent_version_id', sa.UUID(), nullable=True),
    sa.Column('is_draft', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('published_by', sa.Text(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['playbook_id'], ['legal_playbooks.playbook_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.tenant_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('version_id')
    )
    op.create_index(op.f('ix_playbook_versions_playbook_id'), 'playbook_versions', ['playbook_id'], unique=False)
    op.create_table('ai_execution_steps',
    sa.Column('step_id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('step_type', sa.Text(), nullable=False),
    sa.Column('step_order', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'processing', 'completed', 'failed', 'cancelled', 'awaiting_approval', name='ai_step_status'), nullable=False),
    sa.Column('prompt_text', sa.Text(), nullable=True),
    sa.Column('response_text', sa.Text(), nullable=True),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['ai_execution_runs.run_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.tenant_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('step_id')
    )
    op.create_index(op.f('ix_ai_execution_steps_run_id'), 'ai_execution_steps', ['run_id'], unique=False)
    op.create_table('ai_failures',
    sa.Column('failure_id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('failure_type', sa.Text(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=False),
    sa.Column('model_attempted', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['ai_execution_runs.run_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.tenant_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('failure_id')
    )
    op.create_table('ai_findings',
    sa.Column('finding_id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('upload_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('finding_type', sa.Enum('risk', 'classification', 'obligation', 'redline', 'missing_clause', name='finding_type'), nullable=False),
    sa.Column('severity', sa.Enum('critical', 'high', 'medium', 'low', 'info', name='finding_severity'), nullable=False),
    sa.Column('clause_type', sa.Text(), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('recommendation', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('chunk_ids', postgresql.ARRAY(sa.UUID()), nullable=False),
    sa.Column('clause_text', sa.Text(), nullable=True),
    sa.Column('page_numbers', postgresql.ARRAY(sa.Integer()), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['ai_execution_runs.run_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.tenant_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['upload_id'], ['upload_sessions.upload_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('finding_id')
    )
    op.create_index(op.f('ix_ai_findings_run_id'), 'ai_findings', ['run_id'], unique=False)
    op.create_table('ai_redlines',
    sa.Column('redline_id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('upload_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('clause_type', sa.Text(), nullable=True),
    sa.Column('original_text', sa.Text(), nullable=False),
    sa.Column('proposed_text', sa.Text(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('risk_level', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('chunk_ids', postgresql.ARRAY(sa.UUID()), nullable=False),
    sa.Column('page_numbers', postgresql.ARRAY(sa.Integer()), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['ai_execution_runs.run_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.tenant_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['upload_id'], ['upload_sessions.upload_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('redline_id')
    )
    op.create_index(op.f('ix_ai_redlines_run_id'), 'ai_redlines', ['run_id'], unique=False)
    op.create_table('clause_standards',
    sa.Column('clause_id', sa.UUID(), nullable=False),
    sa.Column('playbook_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('category', sa.Enum('indemnification', 'limitation_of_liability', 'confidentiality', 'data_privacy', 'intellectual_property', 'termination', 'governing_law', 'dispute_resolution', 'force_majeure', 'payment_terms', 'warranty', 'insurance', 'compliance', 'audit_rights', 'assignment', 'non_compete', 'non_solicit', 'sla', 'escrow', 'general', name='clause_category'), nullable=False),
    sa.Column('clause_type', sa.Enum('approved', 'preferred', 'fallback', 'forbidden', 'conditional', name='clause_type'), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('fallback_clause_ids', postgresql.ARRAY(sa.UUID()), nullable=False),
    sa.Column('min_contract_value', sa.Float(), nullable=True),
    sa.Column('max_contract_value', sa.Float(), nullable=True),
    sa.Column('applicable_jurisdictions', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('applicable_industries', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('risk_level', sa.Text(), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('playbook_version_id', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('effective_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expiration_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['playbook_id'], ['legal_playbooks.playbook_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['playbook_version_id'], ['playbook_versions.version_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.tenant_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('clause_id')
    )
    op.create_index(op.f('ix_clause_standards_playbook_id'), 'clause_standards', ['playbook_id'], unique=False)
    op.create_index(op.f('ix_clause_standards_tenant_id'), 'clause_standards', ['tenant_id'], unique=False)
    op.create_table('embedding_failures',
    sa.Column('failure_id', sa.UUID(), nullable=False),
    sa.Column('upload_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('chunk_id', sa.UUID(), nullable=True),
    sa.Column('failure_type', sa.Text(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=False),
    sa.Column('model_attempted', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chunk_id'], ['chunks.chunk_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.tenant_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['upload_id'], ['upload_sessions.upload_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('failure_id')
    )
    op.create_table('policy_evaluations',
    sa.Column('evaluation_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('upload_id', sa.UUID(), nullable=False),
    sa.Column('review_id', sa.UUID(), nullable=True),
    sa.Column('playbook_id', sa.UUID(), nullable=True),
    sa.Column('playbook_version_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'processing', 'completed', 'failed', name='eval_status'), nullable=False),
    sa.Column('total_rules_evaluated', sa.Integer(), nullable=False),
    sa.Column('rules_passed', sa.Integer(), nullable=False),
    sa.Column('rules_failed', sa.Integer(), nullable=False),
    sa.Column('deviations_found', sa.Integer(), nullable=False),
    sa.Column('mandatory_blocks', sa.Integer(), nullable=False),
    sa.Column('approval_required', sa.Integer(), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('risk_level', sa.Text(), nullable=True),
    sa.Column('results', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('deviations', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('recommendations', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('correlation_id', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['playbook_id'], ['legal_playbooks.playbook_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['playbook_version_id'], ['playbook_versions.version_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['review_id'], ['contract_reviews.review_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.tenant_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['upload_id'], ['upload_sessions.upload_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('evaluation_id')
    )
    op.create_index(op.f('ix_policy_evaluations_tenant_id'), 'policy_evaluations', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_policy_evaluations_upload_id'), 'policy_evaluations', ['upload_id'], unique=False)
    op.create_table('review_approvals',
    sa.Column('approval_id', sa.UUID(), nullable=False),
    sa.Column('review_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('approver_id', sa.Text(), nullable=False),
    sa.Column('decision', sa.Text(), nullable=False),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('conditions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['review_id'], ['contract_reviews.review_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.tenant_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('approval_id')
    )
    op.create_index(op.f('ix_review_approvals_review_id'), 'review_approvals', ['review_id'], unique=False)
    op.create_table('review_assignments',
    sa.Column('assignment_id', sa.UUID(), nullable=False),
    sa.Column('review_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('assignee_id', sa.Text(), nullable=False),
    sa.Column('assigned_by', sa.Text(), nullable=False),
    sa.Column('role', sa.Text(), nullable=False),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['review_id'], ['contract_reviews.review_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.tenant_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('assignment_id')
    )
    op.create_index(op.f('ix_review_assignments_assignee_id'), 'review_assignments', ['assignee_id'], unique=False)
    op.create_index(op.f('ix_review_assignments_review_id'), 'review_assignments', ['review_id'], unique=False)
    op.create_table('review_comments',
    sa.Column('comment_id', sa.UUID(), nullable=False),
    sa.Column('review_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.Text(), nullable=True),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('parent_comment_id', sa.UUID(), nullable=True),
    sa.Column('author_id', sa.Text(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('mentions', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('is_resolved', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['parent_comment_id'], ['review_comments.comment_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['review_id'], ['contract_reviews.review_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.tenant_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('comment_id')
    )
    op.create_index(op.f('ix_review_comments_review_id'), 'review_comments', ['review_id'], unique=False)
    op.create_table('review_escalations',
    sa.Column('escalation_id', sa.UUID(), nullable=False),
    sa.Column('review_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('escalated_by', sa.Text(), nullable=False),
    sa.Column('escalated_to', sa.Text(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['review_id'], ['contract_reviews.review_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.tenant_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('escalation_id')
    )
    op.create_index(op.f('ix_review_escalations_review_id'), 'review_escalations', ['review_id'], unique=False)
    op.create_table('review_status_history',
    sa.Column('history_id', sa.UUID(), nullable=False),
    sa.Column('review_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('from_status', sa.Text(), nullable=False),
    sa.Column('to_status', sa.Text(), nullable=False),
    sa.Column('changed_by', sa.Text(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['review_id'], ['contract_reviews.review_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.tenant_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('history_id')
    )
    op.create_index(op.f('ix_review_status_history_review_id'), 'review_status_history', ['review_id'], unique=False)
    op.create_table('search_clicks',
    sa.Column('click_id', sa.UUID(), nullable=False),
    sa.Column('query_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('result_position', sa.Integer(), nullable=False),
    sa.Column('result_entity_type', sa.Text(), nullable=False),
    sa.Column('result_entity_id', sa.UUID(), nullable=False),
    sa.Column('chunk_id', sa.UUID(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('dwell_time_ms', sa.Integer(), nullable=True),
    sa.Column('was_conversion', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chunk_id'], ['chunks.chunk_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['query_id'], ['search_queries.query_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.tenant_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('click_id')
    )
    op.create_index(op.f('ix_search_clicks_query_id'), 'search_clicks', ['query_id'], unique=False)
    op.create_table('clause_recommendations',
    sa.Column('recommendation_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('evaluation_id', sa.UUID(), nullable=False),
    sa.Column('upload_id', sa.UUID(), nullable=False),
    sa.Column('review_id', sa.UUID(), nullable=True),
    sa.Column('clause_id', sa.UUID(), nullable=True),
    sa.Column('clause_category', sa.Text(), nullable=False),
    sa.Column('clause_type', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('risk_reduction', sa.Text(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('is_applied', sa.Boolean(), nullable=False),
    sa.Column('applied_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('applied_by', sa.Text(), nullable=True),
    sa.Column('deviation_id', sa.UUID(), nullable=True),
    sa.Column('replaces_clause_text', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['clause_id'], ['clause_standards.clause_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['evaluation_id'], ['policy_evaluations.evaluation_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['review_id'], ['contract_reviews.review_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.tenant_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['upload_id'], ['upload_sessions.upload_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('recommendation_id')
    )
    op.create_index(op.f('ix_clause_recommendations_evaluation_id'), 'clause_recommendations', ['evaluation_id'], unique=False)
    op.create_index(op.f('ix_clause_recommendations_tenant_id'), 'clause_recommendations', ['tenant_id'], unique=False)
    op.create_table('policy_rules',
    sa.Column('rule_id', sa.UUID(), nullable=False),
    sa.Column('playbook_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('rule_type', sa.Text(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_mandatory', sa.Boolean(), nullable=False),
    sa.Column('conditions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('effect', sa.Enum('allow', 'block', 'flag_for_review', 'require_approval', 'require_mandatory_clause', 'recommend_fallback', 'escalate', name='rule_effect'), nullable=False),
    sa.Column('effect_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('target_clause_id', sa.UUID(), nullable=True),
    sa.Column('target_category', sa.Text(), nullable=True),
    sa.Column('applicable_jurisdictions', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('applicable_industries', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('min_contract_value', sa.Float(), nullable=True),
    sa.Column('max_contract_value', sa.Float(), nullable=True),
    sa.Column('effective_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expiration_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_by', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['playbook_id'], ['legal_playbooks.playbook_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_clause_id'], ['clause_standards.clause_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.tenant_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('rule_id')
    )
    op.create_index(op.f('ix_policy_rules_playbook_id'), 'policy_rules', ['playbook_id'], unique=False)
    op.create_index(op.f('ix_policy_rules_tenant_id'), 'policy_rules', ['tenant_id'], unique=False)
    op.create_table('review_findings',
    sa.Column('finding_id', sa.UUID(), nullable=False),
    sa.Column('review_id', sa.UUID(), nullable=False),
    sa.Column('upload_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('ai_finding_id', sa.UUID(), nullable=True),
    sa.Column('clause_type', sa.Text(), nullable=True),
    sa.Column('severity', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('recommendation', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('chunk_ids', postgresql.ARRAY(sa.UUID()), nullable=False),
    sa.Column('page_numbers', postgresql.ARRAY(sa.Integer()), nullable=False),
    sa.Column('resolution', sa.Enum('acknowledged', 'resolved', 'dismissed', 'false_positive', 'escalated', name='finding_resolution'), nullable=True),
    sa.Column('resolution_note', sa.Text(), nullable=True),
    sa.Column('resolved_by', sa.Text(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ai_finding_id'], ['ai_findings.finding_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['review_id'], ['contract_reviews.review_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.tenant_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['upload_id'], ['upload_sessions.upload_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('finding_id')
    )
    op.create_index(op.f('ix_review_findings_review_id'), 'review_findings', ['review_id'], unique=False)
    op.create_table('review_redlines',
    sa.Column('redline_id', sa.UUID(), nullable=False),
    sa.Column('review_id', sa.UUID(), nullable=False),
    sa.Column('upload_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('ai_redline_id', sa.UUID(), nullable=True),
    sa.Column('clause_type', sa.Text(), nullable=True),
    sa.Column('original_text', sa.Text(), nullable=False),
    sa.Column('proposed_text', sa.Text(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('risk_level', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('proposed', 'accepted', 'rejected', 'modified', 'superseded', name='redline_status'), nullable=False),
    sa.Column('reviewer_modified_text', sa.Text(), nullable=True),
    sa.Column('reviewed_by', sa.Text(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ai_redline_id'], ['ai_redlines.redline_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['review_id'], ['contract_reviews.review_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.tenant_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['upload_id'], ['upload_sessions.upload_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('redline_id')
    )
    op.create_index(op.f('ix_review_redlines_review_id'), 'review_redlines', ['review_id'], unique=False)
    op.create_table('policy_overrides',
    sa.Column('override_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('evaluation_id', sa.UUID(), nullable=False),
    sa.Column('rule_id', sa.UUID(), nullable=True),
    sa.Column('upload_id', sa.UUID(), nullable=False),
    sa.Column('review_id', sa.UUID(), nullable=True),
    sa.Column('override_type', sa.Text(), nullable=False),
    sa.Column('justification', sa.Text(), nullable=False),
    sa.Column('risk_assessment', sa.Text(), nullable=True),
    sa.Column('proposed_alternative', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', 'expired', 'cancelled', name='override_status'), nullable=False),
    sa.Column('requested_by', sa.Text(), nullable=False),
    sa.Column('requested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('reviewed_by', sa.Text(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('review_notes', sa.Text(), nullable=True),
    sa.Column('effective_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expiration_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('previous_override_id', sa.UUID(), nullable=True),
    sa.Column('correlation_id', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['evaluation_id'], ['policy_evaluations.evaluation_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['review_id'], ['contract_reviews.review_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['rule_id'], ['policy_rules.rule_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.tenant_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['upload_id'], ['upload_sessions.upload_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('override_id')
    )
    op.create_index(op.f('ix_policy_overrides_evaluation_id'), 'policy_overrides', ['evaluation_id'], unique=False)
    op.create_index(op.f('ix_policy_overrides_tenant_id'), 'policy_overrides', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_policy_overrides_tenant_id'), table_name='policy_overrides')
    op.drop_index(op.f('ix_policy_overrides_evaluation_id'), table_name='policy_overrides')
    op.drop_table('policy_overrides')
    op.drop_index(op.f('ix_review_redlines_review_id'), table_name='review_redlines')
    op.drop_table('review_redlines')
    op.drop_index(op.f('ix_review_findings_review_id'), table_name='review_findings')
    op.drop_table('review_findings')
    op.drop_index(op.f('ix_policy_rules_tenant_id'), table_name='policy_rules')
    op.drop_index(op.f('ix_policy_rules_playbook_id'), table_name='policy_rules')
    op.drop_table('policy_rules')
    op.drop_index(op.f('ix_clause_recommendations_tenant_id'), table_name='clause_recommendations')
    op.drop_index(op.f('ix_clause_recommendations_evaluation_id'), table_name='clause_recommendations')
    op.drop_table('clause_recommendations')
    op.drop_index(op.f('ix_search_clicks_query_id'), table_name='search_clicks')
    op.drop_table('search_clicks')
    op.drop_index(op.f('ix_review_status_history_review_id'), table_name='review_status_history')
    op.drop_table('review_status_history')
    op.drop_index(op.f('ix_review_escalations_review_id'), table_name='review_escalations')
    op.drop_table('review_escalations')
    op.drop_index(op.f('ix_review_comments_review_id'), table_name='review_comments')
    op.drop_table('review_comments')
    op.drop_index(op.f('ix_review_assignments_review_id'), table_name='review_assignments')
    op.drop_index(op.f('ix_review_assignments_assignee_id'), table_name='review_assignments')
    op.drop_table('review_assignments')
    op.drop_index(op.f('ix_review_approvals_review_id'), table_name='review_approvals')
    op.drop_table('review_approvals')
    op.drop_index(op.f('ix_policy_evaluations_upload_id'), table_name='policy_evaluations')
    op.drop_index(op.f('ix_policy_evaluations_tenant_id'), table_name='policy_evaluations')
    op.drop_table('policy_evaluations')
    op.drop_table('embedding_failures')
    op.drop_index(op.f('ix_clause_standards_tenant_id'), table_name='clause_standards')
    op.drop_index(op.f('ix_clause_standards_playbook_id'), table_name='clause_standards')
    op.drop_table('clause_standards')
    op.drop_index(op.f('ix_ai_redlines_run_id'), table_name='ai_redlines')
    op.drop_table('ai_redlines')
    op.drop_index(op.f('ix_ai_findings_run_id'), table_name='ai_findings')
    op.drop_table('ai_findings')
    op.drop_table('ai_failures')
    op.drop_index(op.f('ix_ai_execution_steps_run_id'), table_name='ai_execution_steps')
    op.drop_table('ai_execution_steps')
    op.drop_index(op.f('ix_playbook_versions_playbook_id'), table_name='playbook_versions')
    op.drop_table('playbook_versions')
    op.drop_index(op.f('ix_notification_deliveries_notification_id'), table_name='notification_deliveries')
    op.drop_table('notification_deliveries')
    op.drop_index(op.f('ix_extraction_runs_upload_id'), table_name='extraction_runs')
    op.drop_table('extraction_runs')
    op.drop_index(op.f('ix_extraction_failures_upload_id'), table_name='extraction_failures')
    op.drop_table('extraction_failures')
    op.drop_index(op.f('ix_escalation_events_tenant_id'), table_name='escalation_events')
    op.drop_table('escalation_events')
    op.drop_index(op.f('ix_embedding_runs_upload_id'), table_name='embedding_runs')
    op.drop_table('embedding_runs')
    op.drop_index(op.f('ix_document_pages_upload_id'), table_name='document_pages')
    op.drop_index(op.f('ix_document_pages_tenant_id'), table_name='document_pages')
    op.drop_table('document_pages')
    op.drop_index(op.f('ix_contract_reviews_upload_id'), table_name='contract_reviews')
    op.drop_index(op.f('ix_contract_reviews_tenant_id'), table_name='contract_reviews')
    op.drop_index(op.f('ix_contract_reviews_assigned_to'), table_name='contract_reviews')
    op.drop_table('contract_reviews')
    op.drop_index(op.f('ix_chunks_upload_id'), table_name='chunks')
    op.drop_index(op.f('ix_chunks_tenant_id'), table_name='chunks')
    op.drop_index(op.f('ix_chunks_checksum'), table_name='chunks')
    op.drop_table('chunks')
    op.drop_index(op.f('ix_approval_thresholds_tenant_id'), table_name='approval_thresholds')
    op.drop_index(op.f('ix_approval_thresholds_playbook_id'), table_name='approval_thresholds')
    op.drop_table('approval_thresholds')
    op.drop_index(op.f('ix_ai_execution_runs_upload_id'), table_name='ai_execution_runs')
    op.drop_index(op.f('ix_ai_execution_runs_tenant_id'), table_name='ai_execution_runs')
    op.drop_table('ai_execution_runs')
    op.drop_index(op.f('ix_workflow_timers_tenant_id'), table_name='workflow_timers')
    op.drop_index(op.f('ix_workflow_timers_target_time'), table_name='workflow_timers')
    op.drop_table('workflow_timers')
    op.drop_index(op.f('ix_workflow_events_tenant_id'), table_name='workflow_events')
    op.drop_index(op.f('ix_workflow_events_event_type'), table_name='workflow_events')
    op.drop_table('workflow_events')
    op.drop_index(op.f('ix_upload_sessions_tenant_id'), table_name='upload_sessions')
    op.drop_index(op.f('ix_upload_sessions_ingestion_state'), table_name='upload_sessions')
    op.drop_table('upload_sessions')
    op.drop_table('sla_policies')
    op.drop_index(op.f('ix_semantic_cache_tenant_id'), table_name='semantic_cache')
    op.drop_index(op.f('ix_semantic_cache_query_hash'), table_name='semantic_cache')
    op.drop_index(op.f('ix_semantic_cache_expires_at'), table_name='semantic_cache')
    op.drop_table('semantic_cache')
    op.drop_index(op.f('ix_search_queries_user_id'), table_name='search_queries')
    op.drop_index(op.f('ix_search_queries_tenant_id'), table_name='search_queries')
    op.drop_index(op.f('ix_search_queries_created_at'), table_name='search_queries')
    op.drop_table('search_queries')
    op.drop_table('retrieval_metrics')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_tenant_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_dedup_key'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_created_at'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_notification_preferences_user_id'), table_name='notification_preferences')
    op.drop_table('notification_preferences')
    op.drop_index(op.f('ix_legal_playbooks_tenant_id'), table_name='legal_playbooks')
    op.drop_table('legal_playbooks')
    op.drop_index(op.f('ix_governance_audit_events_tenant_id'), table_name='governance_audit_events')
    op.drop_index(op.f('ix_governance_audit_events_event_type'), table_name='governance_audit_events')
    op.drop_index(op.f('ix_governance_audit_events_created_at'), table_name='governance_audit_events')
    op.drop_table('governance_audit_events')
    op.drop_table('escalation_rules')
    op.drop_index(op.f('ix_ai_cache_entries_tenant_id'), table_name='ai_cache_entries')
    op.drop_index(op.f('ix_ai_cache_entries_prompt_hash'), table_name='ai_cache_entries')
    op.drop_table('ai_cache_entries')
    op.drop_table('tenants')
    op.drop_table('allowed_upload_types')
    op.drop_index(op.f('ix_ai_prompt_versions_prompt_key'), table_name='ai_prompt_versions')
    op.drop_table('ai_prompt_versions')
    # ### end Alembic commands ###
