"""Add approval_override fields to contract_reviews

Revision ID: c96a5c4d44ec
Revises: 7d8e9f0a1b2c
Create Date: 2026-06-10 09:40:04.154545

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c96a5c4d44ec'
down_revision: Union[str, Sequence[str], None] = '7d8e9f0a1b2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_obligation_reminders_obligation_id'), table_name='obligation_reminders')
    op.drop_index(op.f('ix_obligation_reminders_tenant_id'), table_name='obligation_reminders')
    op.drop_table('obligation_reminders')
    op.drop_index(op.f('ix_idempotency_expires'), table_name='idempotency_records', postgresql_where='(expires_at IS NOT NULL)')
    op.drop_index(op.f('ix_idempotency_key_lookup'), table_name='idempotency_records')
    op.drop_index(op.f('ix_idempotency_tenant_operation'), table_name='idempotency_records')
    op.drop_table('idempotency_records')
    op.drop_index(op.f('ix_eval_datasets_prompt_key'), table_name='eval_datasets')
    op.drop_index(op.f('ix_eval_datasets_tenant_id'), table_name='eval_datasets')
    op.drop_table('eval_datasets')
    op.drop_index(op.f('ix_fallback_clauses_category'), table_name='fallback_clauses')
    op.drop_index(op.f('ix_fallback_clauses_tenant_id'), table_name='fallback_clauses')
    op.drop_table('fallback_clauses')
    op.drop_index(op.f('ix_negotiation_history_clause_id'), table_name='negotiation_history')
    op.drop_index(op.f('ix_negotiation_history_tenant_id'), table_name='negotiation_history')
    op.drop_table('negotiation_history')
    op.drop_index(op.f('ix_clause_benchmarks_category'), table_name='clause_benchmarks')
    op.drop_index(op.f('ix_clause_benchmarks_tenant_id'), table_name='clause_benchmarks')
    op.drop_table('clause_benchmarks')
    op.drop_index(op.f('ix_clauses_approval_status'), table_name='clauses')
    op.drop_index(op.f('ix_clauses_category'), table_name='clauses')
    op.drop_index(op.f('ix_clauses_tenant_id'), table_name='clauses')
    op.drop_table('clauses')
    op.drop_index(op.f('ix_sla_metrics_obligation_id'), table_name='sla_metrics')
    op.drop_index(op.f('ix_sla_metrics_tenant_id'), table_name='sla_metrics')
    op.drop_table('sla_metrics')
    op.drop_index(op.f('ix_prompt_templates_prompt_key'), table_name='prompt_templates')
    op.drop_index(op.f('ix_prompt_templates_prompt_key_version'), table_name='prompt_templates')
    op.drop_table('prompt_templates')
    op.drop_index(op.f('ix_scoring_overrides_tenant_id'), table_name='scoring_overrides')
    op.drop_table('scoring_overrides')
    op.drop_index(op.f('ix_obligations_contract_uuid_id'), table_name='obligations')
    op.drop_index(op.f('ix_obligations_due_date'), table_name='obligations')
    op.drop_index(op.f('ix_obligations_obligation_type'), table_name='obligations')
    op.drop_index(op.f('ix_obligations_risk_level'), table_name='obligations')
    op.drop_index(op.f('ix_obligations_sla_status'), table_name='obligations')
    op.drop_index(op.f('ix_obligations_status'), table_name='obligations')
    op.drop_index(op.f('ix_obligations_tenant_id'), table_name='obligations')
    op.drop_index(op.f('ix_obligations_vendor'), table_name='obligations')
    op.drop_table('obligations')
    op.drop_index(op.f('ix_clause_versions_clause_id'), table_name='clause_versions')
    op.drop_index(op.f('ix_clause_versions_tenant_id'), table_name='clause_versions')
    op.drop_table('clause_versions')
    op.drop_index(op.f('ix_clause_usage_clause_id'), table_name='clause_usage')
    op.drop_index(op.f('ix_clause_usage_tenant_id'), table_name='clause_usage')
    op.drop_table('clause_usage')
    op.drop_index(op.f('ix_policy_packs_tenant_id'), table_name='policy_packs')
    op.drop_table('policy_packs')
    op.drop_index(op.f('ix_clause_embeddings_clause_id'), table_name='clause_embeddings')
    op.drop_index(op.f('ix_clause_embeddings_tenant_id'), table_name='clause_embeddings')
    op.drop_table('clause_embeddings')
    op.drop_index(op.f('ix_model_audit_log_created_at'), table_name='model_audit_log')
    op.drop_index(op.f('ix_model_audit_log_tenant_id'), table_name='model_audit_log')
    op.drop_table('model_audit_log')
    op.drop_index(op.f('ix_feature_flag_overrides_flag_key'), table_name='feature_flag_overrides')
    op.drop_index(op.f('ix_feature_flag_overrides_target'), table_name='feature_flag_overrides')
    op.drop_table('feature_flag_overrides')
    op.drop_index(op.f('ix_compliance_packs_tenant_id'), table_name='compliance_packs')
    op.drop_table('compliance_packs')
    op.drop_index(op.f('ix_eval_runs_dataset_id'), table_name='eval_runs')
    op.drop_index(op.f('ix_eval_runs_tenant_id'), table_name='eval_runs')
    op.drop_table('eval_runs')
    op.drop_index(op.f('ix_vendor_performance_tenant_id'), table_name='vendor_performance')
    op.drop_index(op.f('ix_vendor_performance_vendor'), table_name='vendor_performance')
    op.drop_table('vendor_performance')
    op.drop_index(op.f('ix_financial_exposure_category'), table_name='financial_exposure')
    op.drop_index(op.f('ix_financial_exposure_tenant_id'), table_name='financial_exposure')
    op.drop_table('financial_exposure')
    op.drop_index(op.f('ix_obligation_audit_log_contract_uuid_id'), table_name='obligation_audit_log')
    op.drop_index(op.f('ix_obligation_audit_log_obligation_id'), table_name='obligation_audit_log')
    op.drop_index(op.f('ix_obligation_audit_log_tenant_id'), table_name='obligation_audit_log')
    op.drop_table('obligation_audit_log')
    op.drop_index(op.f('ix_obligation_instances_obligation_id'), table_name='obligation_instances')
    op.drop_index(op.f('ix_obligation_instances_tenant_id'), table_name='obligation_instances')
    op.drop_table('obligation_instances')
    op.drop_index(op.f('ix_obligation_evidence_instance_id'), table_name='obligation_evidence')
    op.drop_index(op.f('ix_obligation_evidence_obligation_id'), table_name='obligation_evidence')
    op.drop_index(op.f('ix_obligation_evidence_tenant_id'), table_name='obligation_evidence')
    op.drop_table('obligation_evidence')
    op.drop_index(op.f('ix_event_outbox_correlation_id'), table_name='event_outbox')
    op.drop_index(op.f('ix_event_outbox_created_at'), table_name='event_outbox')
    op.drop_index(op.f('ix_event_outbox_delivery_state'), table_name='event_outbox')
    op.drop_index(op.f('ix_event_outbox_event_type'), table_name='event_outbox')
    op.drop_index(op.f('ix_event_outbox_tenant_id'), table_name='event_outbox')
    op.drop_table('event_outbox')
    op.drop_index(op.f('ix_obligation_escalations_obligation_id'), table_name='obligation_escalations')
    op.drop_index(op.f('ix_obligation_escalations_tenant_id'), table_name='obligation_escalations')
    op.drop_table('obligation_escalations')
    op.drop_constraint(op.f('admin_users_tenant_id_fkey'), 'admin_users', type_='foreignkey')
    op.drop_index(op.f('ix_ai_runs_stuck_recovery'), table_name='ai_execution_runs', postgresql_where="((status = ANY (ARRAY['processing'::ai_exec_status, 'pending'::ai_exec_status])) AND (started_at IS NOT NULL))")
    op.drop_index(op.f('ix_ai_runs_tenant_created'), table_name='ai_execution_runs')
    op.drop_index(op.f('ix_ai_runs_tenant_status'), table_name='ai_execution_runs')
    op.drop_index(op.f('ix_ai_runs_tenant_upload'), table_name='ai_execution_runs')
    op.drop_index(op.f('ix_ai_steps_tenant_run'), table_name='ai_execution_steps')
    op.drop_index(op.f('ix_ai_failures_tenant_created'), table_name='ai_failures')
    op.drop_index(op.f('ix_ai_failures_tenant_type'), table_name='ai_failures')
    op.drop_index(op.f('ix_ai_findings_tenant_run'), table_name='ai_findings')
    op.drop_index(op.f('ix_ai_redlines_tenant_run'), table_name='ai_redlines')
    op.drop_constraint(op.f('audit_export_artifacts_tenant_id_fkey'), 'audit_export_artifacts', type_='foreignkey')
    op.drop_constraint(op.f('audit_export_artifacts_job_id_fkey'), 'audit_export_artifacts', type_='foreignkey')
    op.drop_index(op.f('ix_audit_export_jobs_status'), table_name='audit_export_jobs')
    op.drop_constraint(op.f('audit_export_jobs_tenant_id_fkey'), 'audit_export_jobs', type_='foreignkey')
    op.alter_column('benchmark_clauses', 'category',
               existing_type=sa.TEXT(),
               type_=sa.Enum('indemnification', 'liability_cap', 'termination', 'confidentiality', 'data_privacy', 'compliance', 'payment_terms', 'force_majeure', 'assignment', 'governing_law', 'non_compete', 'ip_ownership', 'auto_renewal', 'sla', 'insurance', 'audit_rights', 'general', name='clause_category'),
               existing_nullable=False)
    op.alter_column('benchmark_corpora', 'source',
               existing_type=sa.TEXT(),
               type_=sa.Enum('uploaded', 'industry_standard', 'aggregated', 'manual', name='corpus_source'),
               existing_nullable=False,
               existing_server_default=sa.text("'uploaded'::text"))
    op.alter_column('benchmark_corpora', 'industry',
               existing_type=sa.TEXT(),
               type_=sa.Enum('technology', 'financial_services', 'healthcare', 'manufacturing', 'retail', 'energy', 'telecom', 'pharmaceutical', 'general', name='corpus_industry'),
               existing_nullable=True)
    op.alter_column('benchmark_corpora', 'geography',
               existing_type=sa.TEXT(),
               type_=sa.Enum('north_america', 'emea', 'apac', 'latam', 'global', name='corpus_geography'),
               existing_nullable=True)
    op.alter_column('benchmark_corpora', 'contract_type',
               existing_type=sa.TEXT(),
               type_=sa.Enum('msa', 'sow', 'nda', 'license', 'service_agreement', 'partnership', 'saas', 'other', name='corpus_contract_type'),
               existing_nullable=True)
    op.drop_constraint(op.f('benchmark_corpora_tenant_id_name_key'), 'benchmark_corpora', type_='unique')
    op.create_unique_constraint('uq_corpus_tenant_name', 'benchmark_corpora', ['tenant_id', 'name'])
    op.alter_column('benchmark_corpus_approvals', 'state',
               existing_type=sa.TEXT(),
               type_=sa.Enum('draft', 'pending_review', 'approved', 'rejected', 'archived', name='approval_state'),
               existing_nullable=False,
               existing_server_default=sa.text("'draft'::text"))
    op.drop_constraint(op.f('benchmark_corpus_versions_corpus_id_version_number_key'), 'benchmark_corpus_versions', type_='unique')
    op.create_unique_constraint('uq_corpus_version', 'benchmark_corpus_versions', ['corpus_id', 'version_number'])
    op.alter_column('benchmark_dedupe_reports', 'severity',
               existing_type=sa.TEXT(),
               type_=sa.Enum('exact', 'near', 'similar', name='dedupe_severity'),
               existing_nullable=False)
    op.alter_column('benchmark_dedupe_reports', 'clause_category',
               existing_type=sa.TEXT(),
               type_=sa.Enum('indemnification', 'liability_cap', 'termination', 'confidentiality', 'data_privacy', 'compliance', 'payment_terms', 'force_majeure', 'assignment', 'governing_law', 'non_compete', 'ip_ownership', 'auto_renewal', 'sla', 'insurance', 'audit_rights', 'general', name='dedupe_clause_category'),
               existing_nullable=True)
    op.alter_column('benchmark_jobs', 'status',
               existing_type=sa.TEXT(),
               type_=sa.Enum('pending', 'running', 'completed', 'failed', 'cancelled', name='benchmark_job_status'),
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::benchmark_job_status"))
    op.alter_column('benchmark_scores', 'category',
               existing_type=sa.TEXT(),
               type_=sa.Enum('indemnification', 'liability_cap', 'termination', 'confidentiality', 'data_privacy', 'compliance', 'payment_terms', 'force_majeure', 'assignment', 'governing_law', 'non_compete', 'ip_ownership', 'auto_renewal', 'sla', 'insurance', 'audit_rights', 'general', name='benchmark_score_category'),
               existing_nullable=False)
    op.drop_constraint(op.f('benchmark_scores_upload_id_corpus_id_category_key'), 'benchmark_scores', type_='unique')
    op.create_unique_constraint('uq_benchmark_score_triple', 'benchmark_scores', ['upload_id', 'corpus_id', 'category'])
    op.alter_column('bulk_actions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_bulk_actions_tenant'), table_name='bulk_actions')
    op.create_index(op.f('ix_bulk_actions_tenant_id'), 'bulk_actions', ['tenant_id'], unique=False)
    op.drop_index(op.f('ix_chunks_tenant_clause'), table_name='chunks')
    op.drop_index(op.f('ix_chunks_tenant_upload'), table_name='chunks')
    op.drop_index(op.f('ix_chunks_text_trgm'), table_name='chunks', postgresql_ops={'text': 'gin_trgm_ops'}, postgresql_using='gin')
    op.drop_index(op.f('uq_assessment_per_framework'), table_name='compliance_assessments')
    op.drop_index(op.f('uq_current_version_per_review'), table_name='contract_document_versions', postgresql_where="(status = 'current'::text)")
    op.drop_index(op.f('uq_finalized_version_per_review'), table_name='contract_document_versions', postgresql_where="(status = 'finalized'::text)")
    op.add_column('contract_reviews', sa.Column('approval_override_reason', sa.Text(), nullable=True))
    op.add_column('contract_reviews', sa.Column('approval_override_by', sa.Text(), nullable=True))
    op.add_column('contract_reviews', sa.Column('approval_override_timestamp', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('contract_reviews', 'sla_status',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("'on_track'::text"))
    op.alter_column('contract_reviews', 'overdue_hours',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.drop_index(op.f('ix_reviews_active'), table_name='contract_reviews', postgresql_where='(is_deleted = false)')
    op.drop_index(op.f('ix_reviews_stuck_recovery'), table_name='contract_reviews', postgresql_where="((is_deleted = false) AND (status = ANY (ARRAY['draft'::review_status, 'ai_analyzed'::review_status])))")
    op.drop_index(op.f('ix_reviews_tenant_assigned'), table_name='contract_reviews', postgresql_where='((is_deleted = false) AND (assigned_to IS NOT NULL))')
    op.drop_index(op.f('ix_reviews_tenant_created'), table_name='contract_reviews', postgresql_where='(is_deleted = false)')
    op.drop_index(op.f('ix_reviews_tenant_priority'), table_name='contract_reviews', postgresql_where='(is_deleted = false)')
    op.drop_index(op.f('ix_reviews_tenant_sla'), table_name='contract_reviews', postgresql_where="((is_deleted = false) AND (sla_deadline IS NOT NULL) AND (status <> ALL (ARRAY['approved'::review_status, 'rejected'::review_status, 'closed'::review_status])))")
    op.drop_index(op.f('ix_reviews_tenant_status'), table_name='contract_reviews', postgresql_where='(is_deleted = false)')
    op.drop_index(op.f('ix_email_queue_created'), table_name='email_queue')
    op.drop_index(op.f('ix_email_queue_status_retry'), table_name='email_queue')
    op.drop_index(op.f('ix_audit_tenant_actor'), table_name='governance_audit_events')
    op.drop_index(op.f('ix_audit_tenant_created'), table_name='governance_audit_events')
    op.drop_index(op.f('ix_audit_tenant_entity'), table_name='governance_audit_events')
    op.drop_index(op.f('ix_audit_tenant_type'), table_name='governance_audit_events')
    op.drop_index(op.f('ix_neg_comments_session_id'), table_name='negotiation_comments')
    op.create_index(op.f('ix_negotiation_comments_session_id'), 'negotiation_comments', ['session_id'], unique=False)
    op.drop_index(op.f('ix_neg_issues_session_id'), table_name='negotiation_issues')
    op.create_index(op.f('ix_negotiation_issues_session_id'), 'negotiation_issues', ['session_id'], unique=False)
    op.drop_index(op.f('ix_neg_participants_session_id'), table_name='negotiation_participants')
    op.create_index(op.f('ix_negotiation_participants_session_id'), 'negotiation_participants', ['session_id'], unique=False)
    op.drop_index(op.f('ix_neg_redlines_clause_id'), table_name='negotiation_redlines')
    op.drop_index(op.f('ix_neg_redlines_session_id'), table_name='negotiation_redlines')
    op.create_index(op.f('ix_negotiation_redlines_clause_id'), 'negotiation_redlines', ['clause_id'], unique=False)
    op.create_index(op.f('ix_negotiation_redlines_session_id'), 'negotiation_redlines', ['session_id'], unique=False)
    op.drop_index(op.f('ix_neg_sessions_contract_id'), table_name='negotiation_sessions')
    op.drop_index(op.f('ix_neg_sessions_stage'), table_name='negotiation_sessions')
    op.drop_index(op.f('ix_neg_sessions_tenant_id'), table_name='negotiation_sessions')
    op.create_index(op.f('ix_negotiation_sessions_contract_id'), 'negotiation_sessions', ['contract_id'], unique=False)
    op.create_index(op.f('ix_negotiation_sessions_stage'), 'negotiation_sessions', ['stage'], unique=False)
    op.create_index(op.f('ix_negotiation_sessions_tenant_id'), 'negotiation_sessions', ['tenant_id'], unique=False)
    op.drop_index(op.f('ix_neg_versions_session_id'), table_name='negotiation_versions')
    op.create_index(op.f('ix_negotiation_versions_session_id'), 'negotiation_versions', ['session_id'], unique=False)
    op.drop_index(op.f('ix_notifications_tenant_user'), table_name='notifications', postgresql_where='(is_read = false)')
    op.create_index(op.f('ix_policy_evaluations_review_id'), 'policy_evaluations', ['review_id'], unique=False)
    op.create_index(op.f('ix_policy_overrides_review_id'), 'policy_overrides', ['review_id'], unique=False)
    op.create_index(op.f('ix_recovery_actions_entity_id'), 'recovery_actions', ['entity_id'], unique=False)
    op.create_index(op.f('ix_recovery_actions_tenant_id'), 'recovery_actions', ['tenant_id'], unique=False)
    op.drop_index(op.f('uq_single_approval_per_review'), table_name='review_approvals', postgresql_where="(decision = 'approved'::text)")
    op.drop_index(op.f('ix_assignments_tenant_assignee'), table_name='review_assignments', postgresql_where='(completed_at IS NULL)')
    op.drop_index(op.f('ix_assignments_tenant_review'), table_name='review_assignments')
    op.drop_constraint(op.f('uq_review_assignee'), 'review_assignments', type_='unique')
    op.drop_index(op.f('ix_comments_tenant_review'), table_name='review_comments', postgresql_where='(deleted_at IS NULL)')
    op.drop_index(op.f('ix_escalations_tenant_review'), table_name='review_escalations')
    op.drop_index(op.f('ix_escalations_tenant_status'), table_name='review_escalations')
    op.drop_index(op.f('ix_findings_tenant_clause'), table_name='review_findings')
    op.drop_index(op.f('ix_findings_tenant_created'), table_name='review_findings')
    op.drop_index(op.f('ix_findings_tenant_resolution'), table_name='review_findings', postgresql_where='(resolution IS NOT NULL)')
    op.drop_index(op.f('ix_findings_tenant_review'), table_name='review_findings')
    op.drop_index(op.f('ix_findings_tenant_severity'), table_name='review_findings')
    op.drop_index(op.f('ix_findings_text_search'), table_name='review_findings', postgresql_using='gin')
    op.drop_index(op.f('ix_findings_title_trgm'), table_name='review_findings', postgresql_ops={'title': 'gin_trgm_ops'}, postgresql_using='gin')
    op.drop_index(op.f('ix_redlines_tenant_review'), table_name='review_redlines')
    op.drop_index(op.f('ix_redlines_tenant_status'), table_name='review_redlines')
    op.drop_index(op.f('ix_review_redlines_finding_id'), table_name='review_redlines')
    op.create_foreign_key(None, 'review_redlines', 'review_findings', ['finding_id'], ['finding_id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_review_history_tenant_created'), table_name='review_status_history')
    op.drop_index(op.f('ix_review_history_tenant_review'), table_name='review_status_history')
    op.drop_index(op.f('ix_risk_delta_review_created'), table_name='risk_delta_events')
    op.drop_index(op.f('ix_risk_delta_tenant_type'), table_name='risk_delta_events')
    op.create_unique_constraint('uq_risk_delta_event', 'risk_delta_events', ['delta_id'])
    op.alter_column('routing_rules', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('routing_rules', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_routing_rules_tenant'), table_name='routing_rules')
    op.create_index(op.f('ix_routing_rules_tenant_id'), 'routing_rules', ['tenant_id'], unique=False)
    op.drop_index(op.f('ix_search_queries_tenant_created'), table_name='search_queries')
    op.drop_index(op.f('ix_search_queries_tenant_popular'), table_name='search_queries', postgresql_where='(result_count > 0)')
    op.drop_constraint(op.f('tenant_settings_tenant_id_key'), 'tenant_settings', type_='unique')
    op.drop_constraint(op.f('tenant_settings_tenant_id_fkey'), 'tenant_settings', type_='foreignkey')
    op.drop_index(op.f('ix_uploads_stuck_recovery'), table_name='upload_sessions', postgresql_where="(ingestion_state <> ALL (ARRAY['review_ready'::ingestion_state, 'failed'::ingestion_state, 'cancelled'::ingestion_state, 'quarantined'::ingestion_state]))")
    op.drop_index(op.f('ix_uploads_tenant_checksum'), table_name='upload_sessions', postgresql_where='(client_checksum_sha256 IS NOT NULL)')
    op.drop_index(op.f('ix_uploads_tenant_created'), table_name='upload_sessions')
    op.drop_index(op.f('ix_uploads_tenant_state'), table_name='upload_sessions')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_uploads_tenant_state'), 'upload_sessions', ['tenant_id', 'ingestion_state'], unique=False)
    op.create_index(op.f('ix_uploads_tenant_created'), 'upload_sessions', ['tenant_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('ix_uploads_tenant_checksum'), 'upload_sessions', ['tenant_id', 'client_checksum_sha256'], unique=False, postgresql_where='(client_checksum_sha256 IS NOT NULL)')
    op.create_index(op.f('ix_uploads_stuck_recovery'), 'upload_sessions', ['tenant_id', 'updated_at'], unique=False, postgresql_where="(ingestion_state <> ALL (ARRAY['review_ready'::ingestion_state, 'failed'::ingestion_state, 'cancelled'::ingestion_state, 'quarantined'::ingestion_state]))")
    op.create_foreign_key(op.f('tenant_settings_tenant_id_fkey'), 'tenant_settings', 'tenants', ['tenant_id'], ['tenant_id'], ondelete='CASCADE')
    op.create_unique_constraint(op.f('tenant_settings_tenant_id_key'), 'tenant_settings', ['tenant_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_search_queries_tenant_popular'), 'search_queries', ['tenant_id', 'query_text', sa.literal_column('created_at DESC')], unique=False, postgresql_where='(result_count > 0)')
    op.create_index(op.f('ix_search_queries_tenant_created'), 'search_queries', ['tenant_id', sa.literal_column('created_at DESC')], unique=False)
    op.drop_index(op.f('ix_routing_rules_tenant_id'), table_name='routing_rules')
    op.create_index(op.f('idx_routing_rules_tenant'), 'routing_rules', ['tenant_id'], unique=False)
    op.alter_column('routing_rules', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('routing_rules', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('uq_risk_delta_event', 'risk_delta_events', type_='unique')
    op.create_index(op.f('ix_risk_delta_tenant_type'), 'risk_delta_events', ['tenant_id', 'delta_type'], unique=False)
    op.create_index(op.f('ix_risk_delta_review_created'), 'risk_delta_events', ['review_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_review_history_tenant_review'), 'review_status_history', ['tenant_id', 'review_id'], unique=False)
    op.create_index(op.f('ix_review_history_tenant_created'), 'review_status_history', ['tenant_id', sa.literal_column('created_at DESC')], unique=False)
    op.drop_constraint(None, 'review_redlines', type_='foreignkey')
    op.create_index(op.f('ix_review_redlines_finding_id'), 'review_redlines', ['finding_id'], unique=False)
    op.create_index(op.f('ix_redlines_tenant_status'), 'review_redlines', ['tenant_id', 'status'], unique=False)
    op.create_index(op.f('ix_redlines_tenant_review'), 'review_redlines', ['tenant_id', 'review_id'], unique=False)
    op.create_index(op.f('ix_findings_title_trgm'), 'review_findings', ['title'], unique=False, postgresql_ops={'title': 'gin_trgm_ops'}, postgresql_using='gin')
    op.create_index(op.f('ix_findings_text_search'), 'review_findings', [sa.literal_column("to_tsvector('english'::regconfig, (((COALESCE(title, ''::text) || ' '::text) || COALESCE(description, ''::text)) || ' '::text) || COALESCE(recommendation, ''::text))")], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_findings_tenant_severity'), 'review_findings', ['tenant_id', 'severity'], unique=False)
    op.create_index(op.f('ix_findings_tenant_review'), 'review_findings', ['tenant_id', 'review_id'], unique=False)
    op.create_index(op.f('ix_findings_tenant_resolution'), 'review_findings', ['tenant_id', 'resolution'], unique=False, postgresql_where='(resolution IS NOT NULL)')
    op.create_index(op.f('ix_findings_tenant_created'), 'review_findings', ['tenant_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('ix_findings_tenant_clause'), 'review_findings', ['tenant_id', 'clause_type'], unique=False)
    op.create_index(op.f('ix_escalations_tenant_status'), 'review_escalations', ['tenant_id', 'status'], unique=False)
    op.create_index(op.f('ix_escalations_tenant_review'), 'review_escalations', ['tenant_id', 'review_id'], unique=False)
    op.create_index(op.f('ix_comments_tenant_review'), 'review_comments', ['tenant_id', 'review_id'], unique=False, postgresql_where='(deleted_at IS NULL)')
    op.create_unique_constraint(op.f('uq_review_assignee'), 'review_assignments', ['review_id', 'assignee_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_assignments_tenant_review'), 'review_assignments', ['tenant_id', 'review_id'], unique=False)
    op.create_index(op.f('ix_assignments_tenant_assignee'), 'review_assignments', ['tenant_id', 'assignee_id'], unique=False, postgresql_where='(completed_at IS NULL)')
    op.create_index(op.f('uq_single_approval_per_review'), 'review_approvals', ['review_id'], unique=True, postgresql_where="(decision = 'approved'::text)")
    op.drop_index(op.f('ix_recovery_actions_tenant_id'), table_name='recovery_actions')
    op.drop_index(op.f('ix_recovery_actions_entity_id'), table_name='recovery_actions')
    op.drop_index(op.f('ix_policy_overrides_review_id'), table_name='policy_overrides')
    op.drop_index(op.f('ix_policy_evaluations_review_id'), table_name='policy_evaluations')
    op.create_index(op.f('ix_notifications_tenant_user'), 'notifications', ['tenant_id', 'user_id', sa.literal_column('created_at DESC')], unique=False, postgresql_where='(is_read = false)')
    op.drop_index(op.f('ix_negotiation_versions_session_id'), table_name='negotiation_versions')
    op.create_index(op.f('ix_neg_versions_session_id'), 'negotiation_versions', ['session_id'], unique=False)
    op.drop_index(op.f('ix_negotiation_sessions_tenant_id'), table_name='negotiation_sessions')
    op.drop_index(op.f('ix_negotiation_sessions_stage'), table_name='negotiation_sessions')
    op.drop_index(op.f('ix_negotiation_sessions_contract_id'), table_name='negotiation_sessions')
    op.create_index(op.f('ix_neg_sessions_tenant_id'), 'negotiation_sessions', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_neg_sessions_stage'), 'negotiation_sessions', ['stage'], unique=False)
    op.create_index(op.f('ix_neg_sessions_contract_id'), 'negotiation_sessions', ['contract_id'], unique=False)
    op.drop_index(op.f('ix_negotiation_redlines_session_id'), table_name='negotiation_redlines')
    op.drop_index(op.f('ix_negotiation_redlines_clause_id'), table_name='negotiation_redlines')
    op.create_index(op.f('ix_neg_redlines_session_id'), 'negotiation_redlines', ['session_id'], unique=False)
    op.create_index(op.f('ix_neg_redlines_clause_id'), 'negotiation_redlines', ['clause_id'], unique=False)
    op.drop_index(op.f('ix_negotiation_participants_session_id'), table_name='negotiation_participants')
    op.create_index(op.f('ix_neg_participants_session_id'), 'negotiation_participants', ['session_id'], unique=False)
    op.drop_index(op.f('ix_negotiation_issues_session_id'), table_name='negotiation_issues')
    op.create_index(op.f('ix_neg_issues_session_id'), 'negotiation_issues', ['session_id'], unique=False)
    op.drop_index(op.f('ix_negotiation_comments_session_id'), table_name='negotiation_comments')
    op.create_index(op.f('ix_neg_comments_session_id'), 'negotiation_comments', ['session_id'], unique=False)
    op.create_index(op.f('ix_audit_tenant_type'), 'governance_audit_events', ['tenant_id', 'event_type'], unique=False)
    op.create_index(op.f('ix_audit_tenant_entity'), 'governance_audit_events', ['tenant_id', 'entity_type', 'entity_id'], unique=False)
    op.create_index(op.f('ix_audit_tenant_created'), 'governance_audit_events', ['tenant_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('ix_audit_tenant_actor'), 'governance_audit_events', ['tenant_id', 'actor_id'], unique=False)
    op.create_index(op.f('ix_email_queue_status_retry'), 'email_queue', ['status', 'next_retry_at'], unique=False)
    op.create_index(op.f('ix_email_queue_created'), 'email_queue', ['created_at'], unique=False)
    op.create_index(op.f('ix_reviews_tenant_status'), 'contract_reviews', ['tenant_id', 'status'], unique=False, postgresql_where='(is_deleted = false)')
    op.create_index(op.f('ix_reviews_tenant_sla'), 'contract_reviews', ['tenant_id', 'sla_deadline'], unique=False, postgresql_where="((is_deleted = false) AND (sla_deadline IS NOT NULL) AND (status <> ALL (ARRAY['approved'::review_status, 'rejected'::review_status, 'closed'::review_status])))")
    op.create_index(op.f('ix_reviews_tenant_priority'), 'contract_reviews', ['tenant_id', 'priority'], unique=False, postgresql_where='(is_deleted = false)')
    op.create_index(op.f('ix_reviews_tenant_created'), 'contract_reviews', ['tenant_id', sa.literal_column('created_at DESC')], unique=False, postgresql_where='(is_deleted = false)')
    op.create_index(op.f('ix_reviews_tenant_assigned'), 'contract_reviews', ['tenant_id', 'assigned_to'], unique=False, postgresql_where='((is_deleted = false) AND (assigned_to IS NOT NULL))')
    op.create_index(op.f('ix_reviews_stuck_recovery'), 'contract_reviews', ['tenant_id', 'updated_at'], unique=False, postgresql_where="((is_deleted = false) AND (status = ANY (ARRAY['draft'::review_status, 'ai_analyzed'::review_status])))")
    op.create_index(op.f('ix_reviews_active'), 'contract_reviews', ['tenant_id', 'review_id'], unique=False, postgresql_where='(is_deleted = false)')
    op.alter_column('contract_reviews', 'overdue_hours',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('contract_reviews', 'sla_status',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("'on_track'::text"))
    op.drop_column('contract_reviews', 'approval_override_timestamp')
    op.drop_column('contract_reviews', 'approval_override_by')
    op.drop_column('contract_reviews', 'approval_override_reason')
    op.create_index(op.f('uq_finalized_version_per_review'), 'contract_document_versions', ['review_id', 'version_number'], unique=True, postgresql_where="(status = 'finalized'::text)")
    op.create_index(op.f('uq_current_version_per_review'), 'contract_document_versions', ['review_id'], unique=True, postgresql_where="(status = 'current'::text)")
    op.create_index(op.f('uq_assessment_per_framework'), 'compliance_assessments', ['tenant_id', 'framework_id'], unique=True)
    op.create_index(op.f('ix_chunks_text_trgm'), 'chunks', ['text'], unique=False, postgresql_ops={'text': 'gin_trgm_ops'}, postgresql_using='gin')
    op.create_index(op.f('ix_chunks_tenant_upload'), 'chunks', ['tenant_id', 'upload_id'], unique=False)
    op.create_index(op.f('ix_chunks_tenant_clause'), 'chunks', ['tenant_id', 'clause_type'], unique=False)
    op.drop_index(op.f('ix_bulk_actions_tenant_id'), table_name='bulk_actions')
    op.create_index(op.f('idx_bulk_actions_tenant'), 'bulk_actions', ['tenant_id'], unique=False)
    op.alter_column('bulk_actions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('uq_benchmark_score_triple', 'benchmark_scores', type_='unique')
    op.create_unique_constraint(op.f('benchmark_scores_upload_id_corpus_id_category_key'), 'benchmark_scores', ['upload_id', 'corpus_id', 'category'], postgresql_nulls_not_distinct=False)
    op.alter_column('benchmark_scores', 'category',
               existing_type=sa.Enum('indemnification', 'liability_cap', 'termination', 'confidentiality', 'data_privacy', 'compliance', 'payment_terms', 'force_majeure', 'assignment', 'governing_law', 'non_compete', 'ip_ownership', 'auto_renewal', 'sla', 'insurance', 'audit_rights', 'general', name='benchmark_score_category'),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('benchmark_jobs', 'status',
               existing_type=sa.Enum('pending', 'running', 'completed', 'failed', 'cancelled', name='benchmark_job_status'),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::benchmark_job_status"))
    op.alter_column('benchmark_dedupe_reports', 'clause_category',
               existing_type=sa.Enum('indemnification', 'liability_cap', 'termination', 'confidentiality', 'data_privacy', 'compliance', 'payment_terms', 'force_majeure', 'assignment', 'governing_law', 'non_compete', 'ip_ownership', 'auto_renewal', 'sla', 'insurance', 'audit_rights', 'general', name='dedupe_clause_category'),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('benchmark_dedupe_reports', 'severity',
               existing_type=sa.Enum('exact', 'near', 'similar', name='dedupe_severity'),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_constraint('uq_corpus_version', 'benchmark_corpus_versions', type_='unique')
    op.create_unique_constraint(op.f('benchmark_corpus_versions_corpus_id_version_number_key'), 'benchmark_corpus_versions', ['corpus_id', 'version_number'], postgresql_nulls_not_distinct=False)
    op.alter_column('benchmark_corpus_approvals', 'state',
               existing_type=sa.Enum('draft', 'pending_review', 'approved', 'rejected', 'archived', name='approval_state'),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("'draft'::text"))
    op.drop_constraint('uq_corpus_tenant_name', 'benchmark_corpora', type_='unique')
    op.create_unique_constraint(op.f('benchmark_corpora_tenant_id_name_key'), 'benchmark_corpora', ['tenant_id', 'name'], postgresql_nulls_not_distinct=False)
    op.alter_column('benchmark_corpora', 'contract_type',
               existing_type=sa.Enum('msa', 'sow', 'nda', 'license', 'service_agreement', 'partnership', 'saas', 'other', name='corpus_contract_type'),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('benchmark_corpora', 'geography',
               existing_type=sa.Enum('north_america', 'emea', 'apac', 'latam', 'global', name='corpus_geography'),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('benchmark_corpora', 'industry',
               existing_type=sa.Enum('technology', 'financial_services', 'healthcare', 'manufacturing', 'retail', 'energy', 'telecom', 'pharmaceutical', 'general', name='corpus_industry'),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('benchmark_corpora', 'source',
               existing_type=sa.Enum('uploaded', 'industry_standard', 'aggregated', 'manual', name='corpus_source'),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("'uploaded'::text"))
    op.alter_column('benchmark_clauses', 'category',
               existing_type=sa.Enum('indemnification', 'liability_cap', 'termination', 'confidentiality', 'data_privacy', 'compliance', 'payment_terms', 'force_majeure', 'assignment', 'governing_law', 'non_compete', 'ip_ownership', 'auto_renewal', 'sla', 'insurance', 'audit_rights', 'general', name='clause_category'),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.create_foreign_key(op.f('audit_export_jobs_tenant_id_fkey'), 'audit_export_jobs', 'tenants', ['tenant_id'], ['tenant_id'], ondelete='CASCADE')
    op.create_index(op.f('ix_audit_export_jobs_status'), 'audit_export_jobs', ['status'], unique=False)
    op.create_foreign_key(op.f('audit_export_artifacts_job_id_fkey'), 'audit_export_artifacts', 'audit_export_jobs', ['job_id'], ['job_id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('audit_export_artifacts_tenant_id_fkey'), 'audit_export_artifacts', 'tenants', ['tenant_id'], ['tenant_id'], ondelete='CASCADE')
    op.create_index(op.f('ix_ai_redlines_tenant_run'), 'ai_redlines', ['tenant_id', 'run_id'], unique=False)
    op.create_index(op.f('ix_ai_findings_tenant_run'), 'ai_findings', ['tenant_id', 'run_id'], unique=False)
    op.create_index(op.f('ix_ai_failures_tenant_type'), 'ai_failures', ['tenant_id', 'failure_type'], unique=False)
    op.create_index(op.f('ix_ai_failures_tenant_created'), 'ai_failures', ['tenant_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('ix_ai_steps_tenant_run'), 'ai_execution_steps', ['tenant_id', 'run_id'], unique=False)
    op.create_index(op.f('ix_ai_runs_tenant_upload'), 'ai_execution_runs', ['tenant_id', 'upload_id'], unique=False)
    op.create_index(op.f('ix_ai_runs_tenant_status'), 'ai_execution_runs', ['tenant_id', 'status'], unique=False)
    op.create_index(op.f('ix_ai_runs_tenant_created'), 'ai_execution_runs', ['tenant_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('ix_ai_runs_stuck_recovery'), 'ai_execution_runs', ['tenant_id', 'started_at'], unique=False, postgresql_where="((status = ANY (ARRAY['processing'::ai_exec_status, 'pending'::ai_exec_status])) AND (started_at IS NOT NULL))")
    op.create_foreign_key(op.f('admin_users_tenant_id_fkey'), 'admin_users', 'tenants', ['tenant_id'], ['tenant_id'], ondelete='CASCADE')
    op.create_table('obligation_escalations',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('obligation_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('escalation_level', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('escalated_to', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('reason', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'active'::character varying"), autoincrement=False, nullable=True),
    sa.Column('resolved_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('resolution_notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['obligation_id'], ['obligations.id'], name=op.f('obligation_escalations_obligation_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.tenant_id'], name=op.f('obligation_escalations_tenant_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('obligation_escalations_pkey'))
    )
    op.create_index(op.f('ix_obligation_escalations_tenant_id'), 'obligation_escalations', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_obligation_escalations_obligation_id'), 'obligation_escalations', ['obligation_id'], unique=False)
    op.create_table('event_outbox',
    sa.Column('event_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('event_type', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('correlation_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('actor_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('delivery_state', sa.TEXT(), server_default=sa.text("'pending'::text"), autoincrement=False, nullable=False),
    sa.Column('delivery_attempts', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('last_error', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('delivered_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('acknowledged_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('dead_letter_reason', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('dead_letter_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('sequence_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('ttl_expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.tenant_id'], name=op.f('event_outbox_tenant_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('event_id', name=op.f('event_outbox_pkey'))
    )
    op.create_index(op.f('ix_event_outbox_tenant_id'), 'event_outbox', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_event_outbox_event_type'), 'event_outbox', ['event_type'], unique=False)
    op.create_index(op.f('ix_event_outbox_delivery_state'), 'event_outbox', ['delivery_state'], unique=False)
    op.create_index(op.f('ix_event_outbox_created_at'), 'event_outbox', ['created_at'], unique=False)
    op.create_index(op.f('ix_event_outbox_correlation_id'), 'event_outbox', ['correlation_id'], unique=False)
    op.create_table('obligation_evidence',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('obligation_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('instance_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('file_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('file_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('file_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('uploaded_by', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['instance_id'], ['obligation_instances.id'], name=op.f('obligation_evidence_instance_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['obligation_id'], ['obligations.id'], name=op.f('obligation_evidence_obligation_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.tenant_id'], name=op.f('obligation_evidence_tenant_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('obligation_evidence_pkey'))
    )
    op.create_index(op.f('ix_obligation_evidence_tenant_id'), 'obligation_evidence', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_obligation_evidence_obligation_id'), 'obligation_evidence', ['obligation_id'], unique=False)
    op.create_index(op.f('ix_obligation_evidence_instance_id'), 'obligation_evidence', ['instance_id'], unique=False)
    op.create_table('obligation_instances',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('obligation_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('instance_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('due_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('completed_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('financial_impact', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['obligation_id'], ['obligations.id'], name=op.f('obligation_instances_obligation_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.tenant_id'], name=op.f('obligation_instances_tenant_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('obligation_instances_pkey'))
    )
    op.create_index(op.f('ix_obligation_instances_tenant_id'), 'obligation_instances', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_obligation_instances_obligation_id'), 'obligation_instances', ['obligation_id'], unique=False)
    op.create_table('obligation_audit_log',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('obligation_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('action', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('actor', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('changes', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('comment', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('contract_uuid_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['contract_uuid_id'], ['contract_reviews.review_id'], name=op.f('obligation_audit_log_contract_uuid_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['obligation_id'], ['obligations.id'], name=op.f('obligation_audit_log_obligation_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.tenant_id'], name=op.f('obligation_audit_log_tenant_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('obligation_audit_log_pkey'))
    )
    op.create_index(op.f('ix_obligation_audit_log_tenant_id'), 'obligation_audit_log', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_obligation_audit_log_obligation_id'), 'obligation_audit_log', ['obligation_id'], unique=False)
    op.create_index(op.f('ix_obligation_audit_log_contract_uuid_id'), 'obligation_audit_log', ['contract_uuid_id'], unique=False)
    op.create_table('financial_exposure',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('category', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('total_exposure', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('overdue_amount', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('at_risk_amount', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('recovered_amount', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('trend', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('currency', sa.VARCHAR(length=10), server_default=sa.text("'USD'::character varying"), autoincrement=False, nullable=True),
    sa.Column('as_of_date', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.tenant_id'], name=op.f('financial_exposure_tenant_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('financial_exposure_pkey'))
    )
    op.create_index(op.f('ix_financial_exposure_tenant_id'), 'financial_exposure', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_financial_exposure_category'), 'financial_exposure', ['category'], unique=False)
    op.create_table('vendor_performance',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('vendor', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('category', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('trend', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('contract_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('breach_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('risk_level', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('predicted_risk', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('last_assessed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.tenant_id'], name=op.f('vendor_performance_tenant_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('vendor_performance_pkey'))
    )
    op.create_index(op.f('ix_vendor_performance_vendor'), 'vendor_performance', ['vendor'], unique=False)
    op.create_index(op.f('ix_vendor_performance_tenant_id'), 'vendor_performance', ['tenant_id'], unique=False)
    op.create_table('eval_runs',
    sa.Column('run_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('dataset_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('prompt_key', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('prompt_version', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('model', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('total_tests', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('passed', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('failed', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('warnings', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('pass_rate', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('avg_latency_ms', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True),
    sa.Column('total_tokens', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['eval_datasets.dataset_id'], name=op.f('eval_runs_dataset_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.tenant_id'], name=op.f('eval_runs_tenant_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('run_id', name=op.f('eval_runs_pkey'))
    )
    op.create_index(op.f('ix_eval_runs_tenant_id'), 'eval_runs', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_eval_runs_dataset_id'), 'eval_runs', ['dataset_id'], unique=False)
    op.create_table('compliance_packs',
    sa.Column('pack_id', sa.VARCHAR(length=12), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('region', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('regulations', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), autoincrement=False, nullable=True),
    sa.Column('required_clause_categories', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), autoincrement=False, nullable=True),
    sa.Column('forbidden_clause_categories', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), autoincrement=False, nullable=True),
    sa.Column('jurisdiction_rules', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('version', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('pack_id', name=op.f('compliance_packs_pkey'))
    )
    op.create_index(op.f('ix_compliance_packs_tenant_id'), 'compliance_packs', ['tenant_id'], unique=False)
    op.create_table('feature_flag_overrides',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('flag_key', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('target_type', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('target_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('enabled', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('feature_flag_overrides_pkey')),
    sa.UniqueConstraint('flag_key', 'target_type', 'target_id', name=op.f('uq_feature_flag_override'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_feature_flag_overrides_target'), 'feature_flag_overrides', ['target_type', 'target_id'], unique=False)
    op.create_index(op.f('ix_feature_flag_overrides_flag_key'), 'feature_flag_overrides', ['flag_key'], unique=False)
    op.create_table('model_audit_log',
    sa.Column('event_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('event_type', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('prompt_key', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('prompt_version', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('model', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('provider', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('duration_ms', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('token_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('cost_usd', sa.NUMERIC(precision=12, scale=6), autoincrement=False, nullable=True),
    sa.Column('success', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('error_type', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('request_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.tenant_id'], name=op.f('model_audit_log_tenant_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('event_id', name=op.f('model_audit_log_pkey'))
    )
    op.create_index(op.f('ix_model_audit_log_tenant_id'), 'model_audit_log', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_model_audit_log_created_at'), 'model_audit_log', ['created_at'], unique=False)
    op.create_table('clause_embeddings',
    sa.Column('embedding_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('clause_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('embedding_model', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('chunk_index', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['clause_id'], ['clauses.clause_id'], name=op.f('clause_embeddings_clause_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.tenant_id'], name=op.f('clause_embeddings_tenant_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('embedding_id', name=op.f('clause_embeddings_pkey')),
    sa.UniqueConstraint('clause_id', name=op.f('clause_embeddings_clause_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_clause_embeddings_tenant_id'), 'clause_embeddings', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_clause_embeddings_clause_id'), 'clause_embeddings', ['clause_id'], unique=False)
    op.create_table('policy_packs',
    sa.Column('pack_id', sa.VARCHAR(length=12), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('scope', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('region', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('industry', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('jurisdiction', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('playbook_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('rule_overrides', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), autoincrement=False, nullable=True),
    sa.Column('threshold_overrides', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), autoincrement=False, nullable=True),
    sa.Column('clause_overrides', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('version', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('pack_id', name=op.f('policy_packs_pkey'))
    )
    op.create_index(op.f('ix_policy_packs_tenant_id'), 'policy_packs', ['tenant_id'], unique=False)
    op.create_table('clause_usage',
    sa.Column('usage_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('clause_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('contract_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('used_as', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('was_accepted', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('was_deviated', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('deviation_reason', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('recorded_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['clause_id'], ['clauses.clause_id'], name=op.f('clause_usage_clause_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.tenant_id'], name=op.f('clause_usage_tenant_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('usage_id', name=op.f('clause_usage_pkey'))
    )
    op.create_index(op.f('ix_clause_usage_tenant_id'), 'clause_usage', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_clause_usage_clause_id'), 'clause_usage', ['clause_id'], unique=False)
    op.create_table('clause_versions',
    sa.Column('version_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('clause_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('version_number', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('risk_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('change_description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['clause_id'], ['clauses.clause_id'], name=op.f('clause_versions_clause_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.tenant_id'], name=op.f('clause_versions_tenant_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('version_id', name=op.f('clause_versions_pkey'))
    )
    op.create_index(op.f('ix_clause_versions_tenant_id'), 'clause_versions', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_clause_versions_clause_id'), 'clause_versions', ['clause_id'], unique=False)
    op.create_table('obligations',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('obligation_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), server_default=sa.text("'pending'::character varying"), autoincrement=False, nullable=True),
    sa.Column('contract_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('contract_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('vendor', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('owner', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('assignee', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('due_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('completed_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('risk_score', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('risk_level', sa.VARCHAR(length=20), server_default=sa.text("'medium'::character varying"), autoincrement=False, nullable=True),
    sa.Column('sla_status', sa.VARCHAR(length=50), server_default=sa.text("'on_track'::character varying"), autoincrement=False, nullable=True),
    sa.Column('sla_remaining_hours', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('financial_impact', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('currency', sa.VARCHAR(length=10), server_default=sa.text("'USD'::character varying"), autoincrement=False, nullable=True),
    sa.Column('escalation_level', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('ai_risk_prediction', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('ai_confidence', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('clause_reference', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('department', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('business_unit', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('geography', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('is_recurring', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('recurrence_pattern', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('recurrence_next_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('attachments_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('reminders_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_favorite', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.TEXT()), server_default=sa.text("'{}'::text[]"), autoincrement=False, nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('contract_uuid_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['contract_uuid_id'], ['contract_reviews.review_id'], name=op.f('obligations_contract_uuid_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.tenant_id'], name=op.f('obligations_tenant_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('obligations_pkey'))
    )
    op.create_index(op.f('ix_obligations_vendor'), 'obligations', ['vendor'], unique=False)
    op.create_index(op.f('ix_obligations_tenant_id'), 'obligations', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_obligations_status'), 'obligations', ['status'], unique=False)
    op.create_index(op.f('ix_obligations_sla_status'), 'obligations', ['sla_status'], unique=False)
    op.create_index(op.f('ix_obligations_risk_level'), 'obligations', ['risk_level'], unique=False)
    op.create_index(op.f('ix_obligations_obligation_type'), 'obligations', ['obligation_type'], unique=False)
    op.create_index(op.f('ix_obligations_due_date'), 'obligations', ['due_date'], unique=False)
    op.create_index(op.f('ix_obligations_contract_uuid_id'), 'obligations', ['contract_uuid_id'], unique=False)
    op.create_table('scoring_overrides',
    sa.Column('override_id', sa.VARCHAR(length=12), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('clause_type', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('override_severity', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('override_risk_weight', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('override_risk_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('reason', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('applies_to_business_units', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('override_id', name=op.f('scoring_overrides_pkey'))
    )
    op.create_index(op.f('ix_scoring_overrides_tenant_id'), 'scoring_overrides', ['tenant_id'], unique=False)
    op.create_table('prompt_templates',
    sa.Column('version_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('prompt_key', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('version_number', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('template', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('system_prompt', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('default_model', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('default_temperature', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('default_max_tokens', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('response_schema', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('state', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('diff_from_previous', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('previous_version_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('version_id', name=op.f('prompt_templates_pkey'))
    )
    op.create_index(op.f('ix_prompt_templates_prompt_key_version'), 'prompt_templates', ['prompt_key', 'version_number'], unique=False)
    op.create_index(op.f('ix_prompt_templates_prompt_key'), 'prompt_templates', ['prompt_key'], unique=False)
    op.create_table('sla_metrics',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('obligation_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('vendor', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('contract_type', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('sla_target', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('performance', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('trend', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('breach_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'on_track'::character varying"), autoincrement=False, nullable=True),
    sa.Column('measured_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['obligation_id'], ['obligations.id'], name=op.f('sla_metrics_obligation_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.tenant_id'], name=op.f('sla_metrics_tenant_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('sla_metrics_pkey'))
    )
    op.create_index(op.f('ix_sla_metrics_tenant_id'), 'sla_metrics', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_sla_metrics_obligation_id'), 'sla_metrics', ['obligation_id'], unique=False)
    op.create_table('clauses',
    sa.Column('clause_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('category', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('clause_type', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('jurisdiction', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('contract_types', postgresql.ARRAY(sa.TEXT()), server_default=sa.text("'{}'::text[]"), autoincrement=False, nullable=False),
    sa.Column('risk_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('risk_level', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('ai_confidence', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('ai_explanation', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('negotiation_strength', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('negotiation_guidance', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('benchmark_percentile', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('usage_frequency', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('approval_status', sa.TEXT(), server_default=sa.text("'draft'::text"), autoincrement=False, nullable=False),
    sa.Column('owner', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('version', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=False),
    sa.Column('is_favorite', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('tags', postgresql.ARRAY(sa.TEXT()), server_default=sa.text("'{}'::text[]"), autoincrement=False, nullable=False),
    sa.Column('governance_notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('deviation_frequency', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('market_percentile', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('playbook_linkage', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.tenant_id'], name=op.f('clauses_tenant_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('clause_id', name=op.f('clauses_pkey'))
    )
    op.create_index(op.f('ix_clauses_tenant_id'), 'clauses', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_clauses_category'), 'clauses', ['category'], unique=False)
    op.create_index(op.f('ix_clauses_approval_status'), 'clauses', ['approval_status'], unique=False)
    op.create_table('clause_benchmarks',
    sa.Column('benchmark_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('category', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('jurisdiction', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('market_median', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('market_p25', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('market_p75', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('sample_size', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('avg_risk_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('acceptance_rate', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('deviation_rate', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.tenant_id'], name=op.f('clause_benchmarks_tenant_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('benchmark_id', name=op.f('clause_benchmarks_pkey'))
    )
    op.create_index(op.f('ix_clause_benchmarks_tenant_id'), 'clause_benchmarks', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_clause_benchmarks_category'), 'clause_benchmarks', ['category'], unique=False)
    op.create_table('negotiation_history',
    sa.Column('history_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('clause_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('counterparty', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('original_text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('negotiated_text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('outcome', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('risk_delta', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('strategy_used', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('success', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['clause_id'], ['clauses.clause_id'], name=op.f('negotiation_history_clause_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.tenant_id'], name=op.f('negotiation_history_tenant_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('history_id', name=op.f('negotiation_history_pkey'))
    )
    op.create_index(op.f('ix_negotiation_history_tenant_id'), 'negotiation_history', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_negotiation_history_clause_id'), 'negotiation_history', ['clause_id'], unique=False)
    op.create_table('fallback_clauses',
    sa.Column('fallback_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('category', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('label', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('risk_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('negotiation_strength', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('usage_rate', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('is_preferred', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('jurisdiction', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.tenant_id'], name=op.f('fallback_clauses_tenant_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('fallback_id', name=op.f('fallback_clauses_pkey'))
    )
    op.create_index(op.f('ix_fallback_clauses_tenant_id'), 'fallback_clauses', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_fallback_clauses_category'), 'fallback_clauses', ['category'], unique=False)
    op.create_table('eval_datasets',
    sa.Column('dataset_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('prompt_key', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('test_cases', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.tenant_id'], name=op.f('eval_datasets_tenant_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('dataset_id', name=op.f('eval_datasets_pkey'))
    )
    op.create_index(op.f('ix_eval_datasets_tenant_id'), 'eval_datasets', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_eval_datasets_prompt_key'), 'eval_datasets', ['prompt_key'], unique=False)
    op.create_table('idempotency_records',
    sa.Column('record_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('idempotency_key', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('operation', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('resource_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('request_hash', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('response_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('status_code', sa.TEXT(), server_default=sa.text("'completed'::text"), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.tenant_id'], name=op.f('idempotency_records_tenant_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('record_id', name=op.f('idempotency_records_pkey'))
    )
    op.create_index(op.f('ix_idempotency_tenant_operation'), 'idempotency_records', ['tenant_id', 'operation'], unique=False)
    op.create_index(op.f('ix_idempotency_key_lookup'), 'idempotency_records', ['idempotency_key'], unique=False)
    op.create_index(op.f('ix_idempotency_expires'), 'idempotency_records', ['expires_at'], unique=False, postgresql_where='(expires_at IS NOT NULL)')
    op.create_table('obligation_reminders',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('obligation_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('reminder_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('remind_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('sent_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'pending'::character varying"), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['obligation_id'], ['obligations.id'], name=op.f('obligation_reminders_obligation_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.tenant_id'], name=op.f('obligation_reminders_tenant_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('obligation_reminders_pkey'))
    )
    op.create_index(op.f('ix_obligation_reminders_tenant_id'), 'obligation_reminders', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_obligation_reminders_obligation_id'), 'obligation_reminders', ['obligation_id'], unique=False)
    # ### end Alembic commands ###
