"""fix vector column

Revision ID: e7b21230c345
Revises: 5772cbcfe2b2
Create Date: 2026-05-15 16:22:55.078188

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision: str = 'e7b21230c345'
down_revision: Union[str, Sequence[str], None] = '5772cbcfe2b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'chunks',
        'embedding',
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        type_=Vector(1536),
        existing_nullable=True,
        postgresql_using='ARRAY[embedding]::vector'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'chunks',
        'embedding',
        existing_type=Vector(1536),
        type_=sa.DOUBLE_PRECISION(precision=53),
        existing_nullable=True
    )
    # ### end Alembic commands ###
