"""Document export module for redline suggestions.

Provides DOCX tracked-changes export and PDF markup export for
redline suggestions generated by the AI redline engine.
"""

from __future__ import annotations

from .docx_exporter import DocxExporter, DocxExportResult
from .tracked_changes import TrackedChangeManager, TrackedChange
from .batch_exporter import BatchExporter, BatchExportResult
from .pdf_exporter import PdfExporter, PdfExportResult
from .annotation_layer import AnnotationLayer, ColorCodedAnnotation
from .summary_page import SummaryPageGenerator

__all__ = [
    "DocxExporter",
    "DocxExportResult",
    "TrackedChangeManager",
    "TrackedChange",
    "BatchExporter",
    "BatchExportResult",
    "PdfExporter",
    "PdfExportResult",
    "AnnotationLayer",
    "ColorCodedAnnotation",
    "SummaryPageGenerator",
]
