"""Seed data for Clause Intelligence — realistic enterprise clause library."""

import uuid
from datetime import datetime, timezone
from sqlalchemy import select, func
from sqlalchemy.ext.asyncio import AsyncSession

from app.domains.clause_intel.models import (
    Clause, ClauseCategory, ClauseBenchmark, FallbackClause,
)

SEED_CLAUSES = [
    {
        "name": "Mutual Indemnification (Standard)",
        "category": ClauseCategory.INDEMNIFICATION,
        "text": "Each party agrees to indemnify, defend, and hold harmless the other party from and against any and all third-party claims arising out of or related to: (a) breach of this Agreement; (b) gross negligence or willful misconduct; or (c) infringement of intellectual property rights. This indemnification shall survive termination of this Agreement.",
        "risk_score": 3.2,
        "risk_level": "low",
        "approval_status": "approved",
        "ai_confidence": 94.0,
        "negotiation_strength": 82.0,
        "usage_frequency": 145,
        "benchmark_percentile": 78.0,
        "version": 3,
        "jurisdiction": "Delaware",
        "contract_types": ["MSA", "SaaS", "Professional Services"],
        "owner": "legal-team",
        "tags": ["indemnification", "mutual", "standard"],
        "ai_explanation": "Standard mutual indemnification clause covering breach, negligence, and IP infringement. Aligns with market standards for enterprise agreements.",
        "negotiation_guidance": "Push for mutual coverage. Carve out IP infringement and confidentiality breach. Cap at reasonable level.",
    },
    {
        "name": "Limitation of Liability — Mutual Cap (2x Fees)",
        "category": ClauseCategory.LIMITATION_OF_LIABILITY,
        "text": "Neither party's aggregate liability arising out of or related to this Agreement shall exceed 200% of the fees paid or payable by Customer during the 12 months preceding the claim. This limitation does not apply to: (a) indemnification obligations; (b) breach of confidentiality; (c) infringement of intellectual property rights; or (d) statutory liabilities.",
        "risk_score": 4.5,
        "risk_level": "medium",
        "approval_status": "approved",
        "ai_confidence": 91.0,
        "negotiation_strength": 75.0,
        "usage_frequency": 198,
        "benchmark_percentile": 72.0,
        "version": 4,
        "jurisdiction": "Delaware",
        "contract_types": ["MSA", "SaaS", "Professional Services", "Consulting"],
        "owner": "legal-team",
        "tags": ["liability", "cap", "mutual", "standard"],
        "ai_explanation": "Mutual liability cap at 2x annual fees with standard exclusions. Market-aligned for enterprise SaaS agreements.",
        "negotiation_guidance": "Resist unlimited liability. Keep mutual. Exclusions are non-negotiable. 2x is standard for enterprise.",
    },
    {
        "name": "Confidentiality — Standard 3-Year Term",
        "category": ClauseCategory.CONFIDENTIALITY,
        "text": "The receiving party shall maintain the confidentiality of the disclosing party's Confidential Information for a period of three (3) years from the date of disclosure. Trade secrets shall be protected indefinitely. Confidential Information includes all written, oral, visual, or electronic information designated as confidential or reasonably understood to be confidential.",
        "risk_score": 2.1,
        "risk_level": "low",
        "approval_status": "approved",
        "ai_confidence": 96.0,
        "negotiation_strength": 88.0,
        "usage_frequency": 234,
        "benchmark_percentile": 85.0,
        "version": 2,
        "jurisdiction": "Delaware",
        "contract_types": ["MSA", "SaaS", "Professional Services", "Consulting", "Partnership"],
        "owner": "legal-team",
        "tags": ["confidentiality", "standard", "survival"],
        "ai_explanation": "Standard confidentiality clause with 3-year term and indefinite trade secret protection. Broad definition of confidential information.",
        "negotiation_guidance": "3-year term is standard. Trade secrets must be perpetual. Definition should be broad enough to cover all business information.",
    },
    {
        "name": "Data Privacy — DPA Required (GDPR Art 28)",
        "category": ClauseCategory.DATA_PRIVACY,
        "text": "The parties shall enter into a Data Processing Agreement in the form attached as Schedule A, which shall govern all processing of personal data. Vendor shall comply with all applicable data protection laws including GDPR, CCPA, and LGPD. Vendor shall notify Customer of any data breach within 24 hours of discovery.",
        "risk_score": 5.8,
        "risk_level": "high",
        "approval_status": "approved",
        "ai_confidence": 93.0,
        "negotiation_strength": 70.0,
        "usage_frequency": 167,
        "benchmark_percentile": 68.0,
        "version": 3,
        "jurisdiction": "Global",
        "contract_types": ["MSA", "SaaS", "Professional Services"],
        "owner": "dpo-team",
        "tags": ["privacy", "dpa", "gdpr", "ccpa", "critical"],
        "ai_explanation": "Requires DPA attachment and 24-hour breach notification. Covers major global privacy regulations. Critical for compliance.",
        "negotiation_guidance": "DPA is non-negotiable. 24-hour breach notification is industry standard. Ensure DPA covers all processing activities.",
    },
    {
        "name": "IP Ownership — Customer Retains Deliverables",
        "category": ClauseCategory.INTELLECTUAL_PROPERTY,
        "text": "All work product, deliverables, software code, documentation, and intellectual property developed specifically for Customer under this Agreement shall be the sole and exclusive property of Customer. Vendor retains ownership of its pre-existing tools and methodologies. Vendor grants Customer a perpetual, irrevocable license to any Vendor pre-existing IP incorporated into deliverables.",
        "risk_score": 3.8,
        "risk_level": "medium",
        "approval_status": "approved",
        "ai_confidence": 90.0,
        "negotiation_strength": 78.0,
        "usage_frequency": 123,
        "benchmark_percentile": 74.0,
        "version": 3,
        "jurisdiction": "Delaware",
        "contract_types": ["Professional Services", "Consulting", "Development"],
        "owner": "legal-team",
        "tags": ["ip", "ownership", "deliverables", "critical"],
        "ai_explanation": "Customer retains full ownership of custom deliverables with license to vendor pre-existing IP. Standard for professional services.",
        "negotiation_guidance": "Customer must own custom deliverables. Vendor pre-existing IP license must be perpetual and irrevocable. No assignment of vendor core IP.",
    },
    {
        "name": "Termination for Convenience — 30 Days",
        "category": ClauseCategory.TERMINATION,
        "text": "Customer may terminate this Agreement for convenience at any time upon thirty (30) days written notice. Vendor may terminate only for material breach by Customer that remains uncured for sixty (60) days. Upon termination, Vendor shall return or destroy all Customer Confidential Information and provide a final invoice for services rendered.",
        "risk_score": 2.5,
        "risk_level": "low",
        "approval_status": "approved",
        "ai_confidence": 95.0,
        "negotiation_strength": 85.0,
        "usage_frequency": 189,
        "benchmark_percentile": 82.0,
        "version": 2,
        "jurisdiction": "Delaware",
        "contract_types": ["MSA", "SaaS", "Professional Services"],
        "owner": "legal-team",
        "tags": ["termination", "convenience", "standard"],
        "ai_explanation": "Customer-only termination for convenience with 30-day notice. Asymmetric termination right favoring customer. Market standard.",
        "negotiation_guidance": "Customer needs unilateral termination right. 30 days is standard. Vendor should only terminate for breach.",
    },
    {
        "name": "Governing Law — Customer Jurisdiction",
        "category": ClauseCategory.GOVERNING_LAW,
        "text": "This Agreement shall be governed by and construed in accordance with the laws of the State of [Customer State], without regard to its conflict of laws principles. The exclusive venue for any disputes shall be the state and federal courts located in [Customer City], [Customer State].",
        "risk_score": 3.0,
        "risk_level": "low",
        "approval_status": "approved",
        "ai_confidence": 97.0,
        "negotiation_strength": 80.0,
        "usage_frequency": 212,
        "benchmark_percentile": 76.0,
        "version": 1,
        "jurisdiction": "Customer State",
        "contract_types": ["MSA", "SaaS", "Professional Services", "Consulting"],
        "owner": "legal-team",
        "tags": ["governing-law", "venue", "jurisdiction"],
        "ai_explanation": "Customer-friendly governing law and venue clause. Standard for customer-procured agreements.",
        "negotiation_guidance": "Keep venue in customer's jurisdiction. Resist vendor forum. Mutual venue is acceptable compromise.",
    },
    {
        "name": "SLA — 99.9% Uptime with Credits",
        "category": ClauseCategory.SLA,
        "text": "Vendor shall maintain service availability of at least 99.9% measured monthly. If availability falls below 99.9%, Customer shall receive service credits of 5% of monthly fees per 0.5% below target. Critical incidents shall have a 30-minute response time. Vendor shall provide monthly SLA reports.",
        "risk_score": 3.5,
        "risk_level": "low",
        "approval_status": "approved",
        "ai_confidence": 92.0,
        "negotiation_strength": 76.0,
        "usage_frequency": 156,
        "benchmark_percentile": 71.0,
        "version": 2,
        "jurisdiction": "Delaware",
        "contract_types": ["SaaS", "Cloud Services"],
        "owner": "it-team",
        "tags": ["sla", "uptime", "service-credits", "standard"],
        "ai_explanation": "Standard 99.9% SLA with tiered service credits and 30-minute critical response. Market-aligned for SaaS.",
        "negotiation_guidance": "99.9% is minimum. Push for 99.95% for critical systems. Credits should be meaningful. Monthly reporting required.",
    },
    {
        "name": "Insurance — Minimum Coverage Requirements",
        "category": ClauseCategory.INSURANCE,
        "text": "Vendor shall maintain the following minimum insurance coverage: (a) Commercial General Liability: $2,000,000 per occurrence; (b) Professional Liability/Errors & Omissions: $3,000,000 per claim; (c) Cyber Liability: $5,000,000 per occurrence; (d) Workers' Compensation: statutory. Vendor shall provide certificates of insurance upon request.",
        "risk_score": 2.8,
        "risk_level": "low",
        "approval_status": "pending_review",
        "ai_confidence": 88.0,
        "negotiation_strength": 72.0,
        "usage_frequency": 98,
        "benchmark_percentile": 65.0,
        "version": 1,
        "jurisdiction": "Delaware",
        "contract_types": ["MSA", "SaaS", "Professional Services"],
        "owner": "risk-team",
        "tags": ["insurance", "coverage", "cyber", "standard"],
        "ai_explanation": "Standard insurance requirements with CGL, E&O, and cyber coverage. Cyber limits may need adjustment based on data sensitivity.",
        "negotiation_guidance": "Cyber insurance is critical. Limits should match data risk. Require 30-day notice of cancellation.",
    },
    {
        "name": "Force Majeure — Standard Excuse",
        "category": ClauseCategory.FORCE_MAJEURE,
        "text": "Neither party shall be liable for delays or failures in performance caused by circumstances beyond its reasonable control, including but not limited to acts of God, war, terrorism, pandemics, government actions, labor disputes, and internet disruptions. The affected party shall provide prompt notice and resume performance as soon as practicable.",
        "risk_score": 1.5,
        "risk_level": "low",
        "approval_status": "approved",
        "ai_confidence": 98.0,
        "negotiation_strength": 90.0,
        "usage_frequency": 178,
        "benchmark_percentile": 88.0,
        "version": 1,
        "jurisdiction": "Delaware",
        "contract_types": ["MSA", "SaaS", "Professional Services", "Consulting"],
        "owner": "legal-team",
        "tags": ["force-majeure", "standard"],
        "ai_explanation": "Standard force majeure clause with broad coverage. Includes pandemic language. Mutual application.",
        "negotiation_guidance": "Keep mutual. Ensure pandemics are included. Payment obligations should survive force majeure.",
    },
    {
        "name": "Warranty — Standard 90-Day Conformance",
        "category": ClauseCategory.WARRANTY,
        "text": "Vendor warrants that the Services will conform in all material respects to the applicable specifications for a period of ninety (90) days following delivery. Vendor further warrants that it has the right to enter into this Agreement and that the Services do not infringe any third-party intellectual property rights.",
        "risk_score": 3.0,
        "risk_level": "low",
        "approval_status": "approved",
        "ai_confidence": 93.0,
        "negotiation_strength": 74.0,
        "usage_frequency": 134,
        "benchmark_percentile": 70.0,
        "version": 2,
        "jurisdiction": "Delaware",
        "contract_types": ["MSA", "SaaS", "Professional Services"],
        "owner": "legal-team",
        "tags": ["warranty", "standard", "conformance"],
        "ai_explanation": "Standard 90-day warranty with IP non-infringement warranty. Market-aligned for enterprise services.",
        "negotiation_guidance": "90-day is standard. Push for 12-month warranty for critical systems. IP warranty is non-negotiable.",
    },
    {
        "name": "Payment Terms — Net 30",
        "category": ClauseCategory.PAYMENT_TERMS,
        "text": "Customer shall pay all invoices within thirty (30) days of receipt. Late payments shall accrue interest at 1.5% per month or the maximum rate permitted by law. Customer may withhold payment of disputed amounts in good faith pending resolution. All fees are non-refundable except as expressly provided herein.",
        "risk_score": 2.0,
        "risk_level": "low",
        "approval_status": "approved",
        "ai_confidence": 96.0,
        "negotiation_strength": 84.0,
        "usage_frequency": 245,
        "benchmark_percentile": 80.0,
        "version": 1,
        "jurisdiction": "Delaware",
        "contract_types": ["MSA", "SaaS", "Professional Services", "Consulting"],
        "owner": "finance-team",
        "tags": ["payment", "terms", "standard"],
        "ai_explanation": "Standard Net 30 payment terms with late fee and dispute withholding rights. Market standard for enterprise.",
        "negotiation_guidance": "Net 30 is standard. Dispute withholding right is important. Late fees should be reasonable.",
    },
]

SEED_BENCHMARKS = [
    {"category": "indemnification", "market_median": 4.2, "market_p25": 3.0, "market_p75": 5.5, "sample_size": 450, "avg_risk_score": 3.8, "acceptance_rate": 0.82, "deviation_rate": 0.15},
    {"category": "limitation_of_liability", "market_median": 5.0, "market_p25": 3.5, "market_p75": 6.5, "sample_size": 520, "avg_risk_score": 4.5, "acceptance_rate": 0.75, "deviation_rate": 0.22},
    {"category": "confidentiality", "market_median": 2.5, "market_p25": 1.8, "market_p75": 3.2, "sample_size": 610, "avg_risk_score": 2.1, "acceptance_rate": 0.92, "deviation_rate": 0.08},
    {"category": "data_privacy", "market_median": 6.0, "market_p25": 4.5, "market_p75": 7.5, "sample_size": 380, "avg_risk_score": 5.8, "acceptance_rate": 0.68, "deviation_rate": 0.30},
    {"category": "intellectual_property", "market_median": 4.5, "market_p25": 3.0, "market_p75": 6.0, "sample_size": 420, "avg_risk_score": 4.2, "acceptance_rate": 0.72, "deviation_rate": 0.25},
    {"category": "termination", "market_median": 3.0, "market_p25": 2.0, "market_p75": 4.0, "sample_size": 480, "avg_risk_score": 2.8, "acceptance_rate": 0.85, "deviation_rate": 0.12},
    {"category": "governing_law", "market_median": 3.5, "market_p25": 2.5, "market_p75": 4.5, "sample_size": 550, "avg_risk_score": 3.0, "acceptance_rate": 0.80, "deviation_rate": 0.18},
    {"category": "sla", "market_median": 4.0, "market_p25": 2.8, "market_p75": 5.2, "sample_size": 350, "avg_risk_score": 3.5, "acceptance_rate": 0.78, "deviation_rate": 0.20},
    {"category": "insurance", "market_median": 3.2, "market_p25": 2.0, "market_p75": 4.5, "sample_size": 290, "avg_risk_score": 2.8, "acceptance_rate": 0.70, "deviation_rate": 0.28},
    {"category": "force_majeure", "market_median": 2.0, "market_p25": 1.0, "market_p75": 3.0, "sample_size": 320, "avg_risk_score": 1.5, "acceptance_rate": 0.95, "deviation_rate": 0.05},
    {"category": "warranty", "market_median": 3.5, "market_p25": 2.5, "market_p75": 4.5, "sample_size": 310, "avg_risk_score": 3.0, "acceptance_rate": 0.76, "deviation_rate": 0.18},
    {"category": "payment_terms", "market_median": 2.5, "market_p25": 1.5, "market_p75": 3.5, "sample_size": 480, "avg_risk_score": 2.0, "acceptance_rate": 0.90, "deviation_rate": 0.10},
]

SEED_FALLBACKS = [
    {"category": "indemnification", "label": "Standard Mutual Indemnification", "text": "Each party agrees to indemnify the other against third-party claims arising from breach of this Agreement, IP infringement, and confidentiality breach. This section shall survive termination.", "risk_score": 3.0, "negotiation_strength": 82, "usage_rate": 0.78, "is_preferred": True, "jurisdiction": "Delaware", "created_by": "system"},
    {"category": "indemnification", "label": "Narrow Vendor Indemnification", "text": "Vendor shall indemnify Customer against all third-party claims arising from the Services. Customer shall indemnify Vendor against claims arising from Customer's use of the Services.", "risk_score": 4.5, "negotiation_strength": 65, "usage_rate": 0.45, "is_preferred": False, "jurisdiction": "Delaware", "created_by": "system"},
    {"category": "limitation_of_liability", "label": "Standard Mutual Cap (2x)", "text": "Each party's total liability shall not exceed the fees paid in the prior 12 months, with exclusions for IP infringement, confidentiality breach, and statutory obligations.", "risk_score": 3.5, "negotiation_strength": 78, "usage_rate": 0.82, "is_preferred": True, "jurisdiction": "Delaware", "created_by": "system"},
    {"category": "limitation_of_liability", "label": "Vendor Cap (3x) / Customer Cap (1x)", "text": "Vendor's liability shall not exceed 3x annual fees. Customer's liability shall not exceed 1x annual fees.", "risk_score": 5.0, "negotiation_strength": 45, "usage_rate": 0.30, "is_preferred": False, "jurisdiction": "Delaware", "created_by": "system"},
    {"category": "confidentiality", "label": "Standard 3-Year Term", "text": "Confidential Information shall be protected for 3 years from disclosure. Trade secrets protected indefinitely. Definition includes all business, technical, and financial information.", "risk_score": 2.0, "negotiation_strength": 88, "usage_rate": 0.90, "is_preferred": True, "jurisdiction": "Delaware", "created_by": "system"},
    {"category": "data_privacy", "label": "Standard DPA + Breach Notification", "text": "Parties shall enter into a DPA. Vendor shall comply with GDPR, CCPA, and LGPD. Breach notification within 24 hours.", "risk_score": 5.5, "negotiation_strength": 90, "usage_rate": 0.85, "is_preferred": True, "jurisdiction": "Global", "created_by": "system"},
]


async def seed_clause_library(session: AsyncSession, tenant_id: str) -> int:
    """Seed the clause library with sample data. Returns number of clauses created."""
    # Check if already seeded
    existing = await session.scalar(
        select(func.count()).select_from(
            select(Clause).where(Clause.tenant_id == uuid.UUID(tenant_id)).subquery()
        )
    )
    if existing and existing > 0:
        return 0  # Already seeded

    tenant_uuid = uuid.UUID(tenant_id)
    now = datetime.now(timezone.utc)
    count = 0

    for data in SEED_CLAUSES:
        clause = Clause(
            clause_id=uuid.uuid4(),
            tenant_id=tenant_uuid,
            name=data["name"],
            category=data["category"],
            text=data["text"],
            risk_score=data["risk_score"],
            risk_level=data["risk_level"],
            approval_status=data["approval_status"],
            ai_confidence=data["ai_confidence"],
            negotiation_strength=data["negotiation_strength"],
            usage_frequency=data["usage_frequency"],
            benchmark_percentile=data["benchmark_percentile"],
            version=data["version"],
            jurisdiction=data["jurisdiction"],
            contract_types=data["contract_types"],
            owner=data["owner"],
            tags=data["tags"],
            ai_explanation=data["ai_explanation"],
            negotiation_guidance=data["negotiation_guidance"],
            created_at=now,
            updated_at=now,
        )
        session.add(clause)
        count += 1

    # Seed benchmarks
    for bm in SEED_BENCHMARKS:
        benchmark = ClauseBenchmark(
            benchmark_id=uuid.uuid4(),
            tenant_id=tenant_uuid,
            category=bm["category"],
            market_median=bm["market_median"],
            market_p25=bm["market_p25"],
            market_p75=bm["market_p75"],
            sample_size=bm["sample_size"],
            avg_risk_score=bm["avg_risk_score"],
            acceptance_rate=bm["acceptance_rate"],
            deviation_rate=bm["deviation_rate"],
            created_at=now,
        )
        session.add(benchmark)

    # Seed fallbacks
    for fb in SEED_FALLBACKS:
        fallback = FallbackClause(
            fallback_id=uuid.uuid4(),
            tenant_id=tenant_uuid,
            category=fb["category"],
            label=fb["label"],
            text=fb["text"],
            risk_score=fb["risk_score"],
            negotiation_strength=fb["negotiation_strength"],
            usage_rate=fb["usage_rate"],
            is_preferred=fb["is_preferred"],
            jurisdiction=fb["jurisdiction"],
            created_by=fb["created_by"],
            created_at=now,
        )
        session.add(fallback)

    await session.commit()
    return count
